package com.swv.oscar.dataobject.common;

import java.io.Serializable;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 * Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0cp12 implements Serializable {

    private String gAttr;
    public String getgAttr() {
        return gAttr;
    }

    public void setgAttr(String gAttr ) {
        this.gAttr = gAttr;
    }

    @Override
    public String toString() {
        return "Weo0cp12 [gAttr =" + gAttr+ "]";
    }
}