package com.swv.oscar.dataobject.common;

import java.io.Serializable;
import java.util.List;

/*************************************************************************
 *
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2017 HCL. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0fcnlBO extends BaseBO implements Serializable {

    private List<Weo0fcnl> weo0fcnl;
    public List<Weo0fcnl> getWeo0fcnl() {
        return weo0fcnl;
    }

    public void setWeo0fcnl(List<Weo0fcnl> weo0fcnl ) {
        this.weo0fcnl = weo0fcnl;
    }

    @Override
    public String toString() {
        return "Weo0fcnlBO [weo0fcnl =" + weo0fcnl+ "]";
    }
}