package com.swv.oscar.dataobject.common;

import java.io.Serializable;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 * Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0s001 implements Serializable {

    private String rPanel;
    private String com;
    private String caseDisplayNbr;
    private String caseNbr;
    private String filler;
    private String gStackedPanel;
    private String gPanel;
    private String gCommand;
    private String gStackedMode;
    private String gAttr;
    private String gPermSsn;
    public String getrPanel() {
        return rPanel;
    }

    public void setrPanel(String rPanel ) {
        this.rPanel = rPanel;
    }

    public String getCom() {
        return com;
    }

    public void setCom(String com ) {
        this.com = com;
    }

    public String getCaseDisplayNbr() {
        return caseDisplayNbr;
    }

    public void setCaseDisplayNbr(String caseDisplayNbr ) {
        this.caseDisplayNbr = caseDisplayNbr;
    }

    public String getCaseNbr() {
        return caseNbr;
    }

    public void setCaseNbr(String caseNbr ) {
        this.caseNbr = caseNbr;
    }

    public String getFiller() {
        return filler;
    }

    public void setFiller(String filler ) {
        this.filler = filler;
    }

    public String getgStackedPanel() {
        return gStackedPanel;
    }

    public void setgStackedPanel(String gStackedPanel ) {
        this.gStackedPanel = gStackedPanel;
    }

    public String getgPanel() {
        return gPanel;
    }

    public void setgPanel(String gPanel ) {
        this.gPanel = gPanel;
    }

    public String getgCommand() {
        return gCommand;
    }

    public void setgCommand(String gCommand ) {
        this.gCommand = gCommand;
    }

    public String getgStackedMode() {
        return gStackedMode;
    }

    public void setgStackedMode(String gStackedMode ) {
        this.gStackedMode = gStackedMode;
    }

    public String getgAttr() {
        return gAttr;
    }

    public void setgAttr(String gAttr ) {
        this.gAttr = gAttr;
    }


    public String getgPermSsn() {
        return gPermSsn;
    }

    public void setgPermSsn(String gPermSsn ) {
        this.gPermSsn = gPermSsn;
    }

    @Override
    public String toString() {
        return "Weo0s001 [rPanel =" + rPanel + " ,com =" + com + " ,caseDisplayNbr =" + caseDisplayNbr + " ,caseNbr =" + caseNbr + " ,filler =" + filler + " ,gStackedPanel =" + gStackedPanel + " ,gPanel =" + gPanel + " ,gCommand =" + gCommand + " ,gStackedMode =" + gStackedMode + " ,gAttr =" + gAttr + "  ,gPermSsn =" + gPermSsn+ "]";
    }
}