package com.swv.oscar.dataobject.common;

import java.io.Serializable;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 * Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0s002 implements Serializable {

    private String mode;
    private String region;
    private String wRegion;
    private String caseIdReqd;
    private String spluCaseload;
    private String wRole;
    private String updateableRole;
    private String gWorkerUid;
    private String gUpdatable;
    private String gTitle;
    private String gPanel;
    private String gApplFlag;
    private String gCaseload;
    private String gRoleId;
    private String gCaseId;
    public String getMode() {
        return mode;
    }

    public void setMode(String mode ) {
        this.mode = mode;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region ) {
        this.region = region;
    }

    public String getwRegion() {
        return wRegion;
    }

    public void setwRegion(String wRegion ) {
        this.wRegion = wRegion;
    }

    public String getCaseIdReqd() {
        return caseIdReqd;
    }

    public void setCaseIdReqd(String caseIdReqd ) {
        this.caseIdReqd = caseIdReqd;
    }

    public String getSpluCaseload() {
        return spluCaseload;
    }

    public void setSpluCaseload(String spluCaseload ) {
        this.spluCaseload = spluCaseload;
    }

    public String getwRole() {
        return wRole;
    }

    public void setwRole(String wRole ) {
        this.wRole = wRole;
    }

    public String getUpdateableRole() {
        return updateableRole;
    }

    public void setUpdateableRole(String updateableRole ) {
        this.updateableRole = updateableRole;
    }

    public String getgWorkerUid() {
        return gWorkerUid;
    }

    public void setgWorkerUid(String gWorkerUid ) {
        this.gWorkerUid = gWorkerUid;
    }

    public String getgUpdatable() {
        return gUpdatable;
    }

    public void setgUpdatable(String gUpdatable ) {
        this.gUpdatable = gUpdatable;
    }

    public String getgTitle() {
        return gTitle;
    }

    public void setgTitle(String gTitle ) {
        this.gTitle = gTitle;
    }


    public String getgPanel() {
        return gPanel;
    }

    public void setgPanel(String gPanel ) {
        this.gPanel = gPanel;
    }


    public String getgApplFlag() {
        return gApplFlag;
    }

    public void setgApplFlag(String gApplFlag ) {
        this.gApplFlag = gApplFlag;
    }


    public String getgCaseload() {
        return gCaseload;
    }

    public void setgCaseload(String gCaseload ) {
        this.gCaseload = gCaseload;
    }

    public String getgRoleId() {
        return gRoleId;
    }

    public void setgRoleId(String gRoleId ) {
        this.gRoleId = gRoleId;
    }


    public String getgCaseId() {
        return gCaseId;
    }

    public void setgCaseId(String gCaseId ) {
        this.gCaseId = gCaseId;
    }

    @Override
    public String toString() {
        return "Weo0s002 [mode =" + mode + " ,region =" + region + " ,wRegion =" + wRegion + " ,caseIdReqd =" + caseIdReqd + " ,spluCaseload =" + spluCaseload + " ,wRole =" + wRole + " ,updateableRole =" + updateableRole + " ,gWorkerUid =" + gWorkerUid + " ,gUpdatable =" + gUpdatable + " ,gTitle =" + gTitle + " ,gPanel =" + gPanel + " ,gApplFlag =" + gApplFlag + " ,gCaseload =" + gCaseload + ",gRoleId =" + gRoleId + " ,gCaseId =" + gCaseId+ "]";
    }
}