package com.swv.oscar.dataobject.common;

import java.io.Serializable;

/*************************************************************************
 *
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2017 HCL. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0g000 implements Serializable {

    private String gApId;
    private String gApSsn;
    private String gApName;
    private String gApLast;
    private String gApFirst;
    private String gApMi;
    private String gApMod;
    private int gApPin;
    private String gFipsNbr;
    private String gCountyCd;
    private String gCaseload;
    private int gCaseId;
    private String gCaseNbr;
    private String gCaseType;
    private String gOosCaseType;
    private String gCtId;
    private String gCtSsn;
    private String gCtName;
    private String gCtLast;
    private String gCtFirst;
    private String gCtMi;
    private String gCtMod;
    private int gCtPin;
    private String gApplicantId;
    private String gEnv;
    private String gSqlid;
    private String gAttr;
    private String gPopMode;
    private String gValidated;
    private String gTitle;
    private String gSubtitle;
    private String gProgram;
    private String gPanel;
    private String gStackedData;
    private String gStackedMode;
    private String gStackedPanel;
    private int gStackedPin;
    private boolean gCv;
    private String gCommand;
    private String gUpdatable;
    private String gSqlstmt;
    private int gSqlstmtl;
    private String gSqlca;
    private String gSqlcaid;
    private int gSqlcabc;
    private int gSqlcode;
    private int gSqlerrml;
    private String gSqlerrm;
    private String gSqlerrp;
    private int gSqlerrd;
    private String gSqlwarn0;
    private String gSqlwarn1;
    private String gSqlwarn2;
    private String gSqlwarn3;
    private String gSqlwarn4;
    private String gSqlwarn5;
    private String gSqlwarn6;
    private String gSqlwarn7;
    private String gSqlext;
    private int gRc;
    private String gTodaysDt;
    private String gPeriodDt;
    private String gBatchNbr;
    private String gCheckNbr;
    private int gClaimNumber;
    private String gReceiptId;
    private String gFromDate;
    private String gCommitData;
    private String gStartTime;
    private String gEndTime;
    private int gCommitMax;
    private String gPrevPanel;
    private String gCheckDt;
    private String gPrevMenu;
    private String globalProgramArea;
    private String gAfdcCommArea;
    private String gAfdcId;
    private String gAfdcTimeCreated;
    private int gAfdcChildNbr;
    private int gAfdcChildPin;
    private int gAfdcXferCases;
    private String gAfdcUpdateFlag;
    private String gWorkerUid;
    private String gChildFlg;
    private int gCurNbr;
    private String gTracDate;
    private String gTblNbr;
    private String gTblName;
    private String gArgCd;
    private int gArgLen;
    private String gResult;
    private int gResLen;
    private int gTaskId;
    private int gEventId;
    private String gTextId;
    private String gSectionNbr;
    private String gTransmittalNbr;
    private String gReference;
    private int gSubscriberId;
    private String gProgramType;
    private String gPolicyUser;
    private String gApplFlag;
    private int gMsgNbr;
    private String gText1;
    private String gText2;
    private String gPermSsn;
    private String gPermLast;
    private String gPermFirst;
    private String gPermMiddle;
    private String gPermMod;
    private String gPermSex;
    private String gPermBirthDate;
    private int gPermPin;
    private int gPcktId;
    private String gTime;
    private String gSubject;
    private String gLastName;
    private int gcsCaseId;
    private String gEnforce;
    private String gHearingDt;
    private String gHearingTime;
    private String gCan;
    private String gCanCountyCd;
    private String gCanStatus;
    private String gJudgeFlmId;
    private String gJudgeFlmType;
    private String gCourtType;
    private String gOosDocketNbr;
    private String gTempOrdrFlag;
    private int gPageNo;
    private String gCaptionFlag;
    private String gProgramArea1;
    private String gProgramArea2;
    private String gRoleId;
    private String gRegion;
    private int gInvsId;
    private String gApptUid;
    private String gForm;
    private String gForm1;
    private String gFqt;
    private int gQCnt;
    private String gFormFlag;
    private String gFormTimestamp;
    private int gAssetId;
    private String gCanMultiDef;
    private int gMultiDefCaseId;
    public String getgApId() {
        return gApId;
    }

    public void setgApId(String gApId ) {
        this.gApId = gApId;
    }

    public String getgApSsn() {
        return gApSsn;
    }

    public void setgApSsn(String gApSsn ) {
        this.gApSsn = gApSsn;
    }

    public String getgApName() {
        return gApName;
    }

    public void setgApName(String gApName ) {
        this.gApName = gApName;
    }

    public String getgApLast() {
        return gApLast;
    }

    public void setgApLast(String gApLast ) {
        this.gApLast = gApLast;
    }

    public String getgApFirst() {
        return gApFirst;
    }

    public void setgApFirst(String gApFirst ) {
        this.gApFirst = gApFirst;
    }

    public String getgApMi() {
        return gApMi;
    }

    public void setgApMi(String gApMi ) {
        this.gApMi = gApMi;
    }

    public String getgApMod() {
        return gApMod;
    }

    public void setgApMod(String gApMod ) {
        this.gApMod = gApMod;
    }

    public int getgApPin() {
        return gApPin;
    }

    public void setgApPin(int gApPin ) {
        this.gApPin = gApPin;
    }

    public String getgFipsNbr() {
        return gFipsNbr;
    }

    public void setgFipsNbr(String gFipsNbr ) {
        this.gFipsNbr = gFipsNbr;
    }

    public String getgCountyCd() {
        return gCountyCd;
    }

    public void setgCountyCd(String gCountyCd ) {
        this.gCountyCd = gCountyCd;
    }

    public String getgCaseload() {
        return gCaseload;
    }

    public void setgCaseload(String gCaseload ) {
        this.gCaseload = gCaseload;
    }

    public int getgCaseId() {
        return gCaseId;
    }

    public void setgCaseId(int gCaseId ) {
        this.gCaseId = gCaseId;
    }

    public String getgCaseNbr() {
        return gCaseNbr;
    }

    public void setgCaseNbr(String gCaseNbr ) {
        this.gCaseNbr = gCaseNbr;
    }

    public String getgCaseType() {
        return gCaseType;
    }

    public void setgCaseType(String gCaseType ) {
        this.gCaseType = gCaseType;
    }

    public String getgOosCaseType() {
        return gOosCaseType;
    }

    public void setgOosCaseType(String gOosCaseType ) {
        this.gOosCaseType = gOosCaseType;
    }

    public String getgCtId() {
        return gCtId;
    }

    public void setgCtId(String gCtId ) {
        this.gCtId = gCtId;
    }

    public String getgCtSsn() {
        return gCtSsn;
    }

    public void setgCtSsn(String gCtSsn ) {
        this.gCtSsn = gCtSsn;
    }

    public String getgCtName() {
        return gCtName;
    }

    public void setgCtName(String gCtName ) {
        this.gCtName = gCtName;
    }

    public String getgCtLast() {
        return gCtLast;
    }

    public void setgCtLast(String gCtLast ) {
        this.gCtLast = gCtLast;
    }

    public String getgCtFirst() {
        return gCtFirst;
    }

    public void setgCtFirst(String gCtFirst ) {
        this.gCtFirst = gCtFirst;
    }

    public String getgCtMi() {
        return gCtMi;
    }

    public void setgCtMi(String gCtMi ) {
        this.gCtMi = gCtMi;
    }

    public String getgCtMod() {
        return gCtMod;
    }

    public void setgCtMod(String gCtMod ) {
        this.gCtMod = gCtMod;
    }

    public int getgCtPin() {
        return gCtPin;
    }

    public void setgCtPin(int gCtPin ) {
        this.gCtPin = gCtPin;
    }

    public String getgApplicantId() {
        return gApplicantId;
    }

    public void setgApplicantId(String gApplicantId ) {
        this.gApplicantId = gApplicantId;
    }

    public String getgEnv() {
        return gEnv;
    }

    public void setgEnv(String gEnv ) {
        this.gEnv = gEnv;
    }

    public String getgSqlid() {
        return gSqlid;
    }

    public void setgSqlid(String gSqlid ) {
        this.gSqlid = gSqlid;
    }

    public String getgAttr() {
        return gAttr;
    }

    public void setgAttr(String gAttr ) {
        this.gAttr = gAttr;
    }

    public String getgPopMode() {
        return gPopMode;
    }

    public void setgPopMode(String gPopMode ) {
        this.gPopMode = gPopMode;
    }

    public String getgValidated() {
        return gValidated;
    }

    public void setgValidated(String gValidated ) {
        this.gValidated = gValidated;
    }

    public String getgTitle() {
        return gTitle;
    }

    public void setgTitle(String gTitle ) {
        this.gTitle = gTitle;
    }

    public String getgSubtitle() {
        return gSubtitle;
    }

    public void setgSubtitle(String gSubtitle ) {
        this.gSubtitle = gSubtitle;
    }

    public String getgProgram() {
        return gProgram;
    }

    public void setgProgram(String gProgram ) {
        this.gProgram = gProgram;
    }

    public String getgPanel() {
        return gPanel;
    }

    public void setgPanel(String gPanel ) {
        this.gPanel = gPanel;
    }

    public String getgStackedData() {
        return gStackedData;
    }

    public void setgStackedData(String gStackedData ) {
        this.gStackedData = gStackedData;
    }


    public String getgStackedMode() {
        return gStackedMode;
    }

    public void setgStackedMode(String gStackedMode ) {
        this.gStackedMode = gStackedMode;
    }

    public String getgStackedPanel() {
        return gStackedPanel;
    }

    public void setgStackedPanel(String gStackedPanel ) {
        this.gStackedPanel = gStackedPanel;
    }

    public int getgStackedPin() {
        return gStackedPin;
    }

    public void setgStackedPin(int gStackedPin ) {
        this.gStackedPin = gStackedPin;
    }

    public boolean getgCv() {
        return gCv;
    }

    public void setgCv(boolean gCv ) {
        this.gCv = gCv;
    }

    public String getgCommand() {
        return gCommand;
    }

    public void setgCommand(String gCommand ) {
        this.gCommand = gCommand;
    }

    public String getgUpdatable() {
        return gUpdatable;
    }

    public void setgUpdatable(String gUpdatable ) {
        this.gUpdatable = gUpdatable;
    }

    public String getgSqlstmt() {
        return gSqlstmt;
    }

    public void setgSqlstmt(String gSqlstmt ) {
        this.gSqlstmt = gSqlstmt;
    }

    public int getgSqlstmtl() {
        return gSqlstmtl;
    }

    public void setgSqlstmtl(int gSqlstmtl ) {
        this.gSqlstmtl = gSqlstmtl;
    }

    public String getgSqlca() {
        return gSqlca;
    }

    public void setgSqlca(String gSqlca ) {
        this.gSqlca = gSqlca;
    }

    public String getgSqlcaid() {
        return gSqlcaid;
    }

    public void setgSqlcaid(String gSqlcaid ) {
        this.gSqlcaid = gSqlcaid;
    }

    public int getgSqlcabc() {
        return gSqlcabc;
    }

    public void setgSqlcabc(int gSqlcabc ) {
        this.gSqlcabc = gSqlcabc;
    }

    public int getgSqlcode() {
        return gSqlcode;
    }

    public void setgSqlcode(int gSqlcode ) {
        this.gSqlcode = gSqlcode;
    }

    public int getgSqlerrml() {
        return gSqlerrml;
    }

    public void setgSqlerrml(int gSqlerrml ) {
        this.gSqlerrml = gSqlerrml;
    }

    public String getgSqlerrm() {
        return gSqlerrm;
    }

    public void setgSqlerrm(String gSqlerrm ) {
        this.gSqlerrm = gSqlerrm;
    }

    public String getgSqlerrp() {
        return gSqlerrp;
    }

    public void setgSqlerrp(String gSqlerrp ) {
        this.gSqlerrp = gSqlerrp;
    }

    public int getgSqlerrd() {
        return gSqlerrd;
    }

    public void setgSqlerrd(int gSqlerrd ) {
        this.gSqlerrd = gSqlerrd;
    }

    public String getgSqlwarn0() {
        return gSqlwarn0;
    }

    public void setgSqlwarn0(String gSqlwarn0 ) {
        this.gSqlwarn0 = gSqlwarn0;
    }

    public String getgSqlwarn1() {
        return gSqlwarn1;
    }

    public void setgSqlwarn1(String gSqlwarn1 ) {
        this.gSqlwarn1 = gSqlwarn1;
    }

    public String getgSqlwarn2() {
        return gSqlwarn2;
    }

    public void setgSqlwarn2(String gSqlwarn2 ) {
        this.gSqlwarn2 = gSqlwarn2;
    }

    public String getgSqlwarn3() {
        return gSqlwarn3;
    }

    public void setgSqlwarn3(String gSqlwarn3 ) {
        this.gSqlwarn3 = gSqlwarn3;
    }

    public String getgSqlwarn4() {
        return gSqlwarn4;
    }

    public void setgSqlwarn4(String gSqlwarn4 ) {
        this.gSqlwarn4 = gSqlwarn4;
    }

    public String getgSqlwarn5() {
        return gSqlwarn5;
    }

    public void setgSqlwarn5(String gSqlwarn5 ) {
        this.gSqlwarn5 = gSqlwarn5;
    }

    public String getgSqlwarn6() {
        return gSqlwarn6;
    }

    public void setgSqlwarn6(String gSqlwarn6 ) {
        this.gSqlwarn6 = gSqlwarn6;
    }

    public String getgSqlwarn7() {
        return gSqlwarn7;
    }

    public void setgSqlwarn7(String gSqlwarn7 ) {
        this.gSqlwarn7 = gSqlwarn7;
    }

    public String getgSqlext() {
        return gSqlext;
    }

    public void setgSqlext(String gSqlext ) {
        this.gSqlext = gSqlext;
    }

    public int getgRc() {
        return gRc;
    }

    public void setgRc(int gRc ) {
        this.gRc = gRc;
    }

    public String getgTodaysDt() {
        return gTodaysDt;
    }

    public void setgTodaysDt(String gTodaysDt ) {
        this.gTodaysDt = gTodaysDt;
    }

    public String getgPeriodDt() {
        return gPeriodDt;
    }

    public void setgPeriodDt(String gPeriodDt ) {
        this.gPeriodDt = gPeriodDt;
    }

    public String getgBatchNbr() {
        return gBatchNbr;
    }

    public void setgBatchNbr(String gBatchNbr ) {
        this.gBatchNbr = gBatchNbr;
    }

    public String getgCheckNbr() {
        return gCheckNbr;
    }

    public void setgCheckNbr(String gCheckNbr ) {
        this.gCheckNbr = gCheckNbr;
    }

    public int getgClaimNumber() {
        return gClaimNumber;
    }

    public void setgClaimNumber(int gClaimNumber ) {
        this.gClaimNumber = gClaimNumber;
    }

    public String getgReceiptId() {
        return gReceiptId;
    }

    public void setgReceiptId(String gReceiptId ) {
        this.gReceiptId = gReceiptId;
    }

    public String getgFromDate() {
        return gFromDate;
    }

    public void setgFromDate(String gFromDate ) {
        this.gFromDate = gFromDate;
    }

    public String getgCommitData() {
        return gCommitData;
    }

    public void setgCommitData(String gCommitData ) {
        this.gCommitData = gCommitData;
    }

    public String getgStartTime() {
        return gStartTime;
    }

    public void setgStartTime(String gStartTime ) {
        this.gStartTime = gStartTime;
    }

    public String getgEndTime() {
        return gEndTime;
    }

    public void setgEndTime(String gEndTime ) {
        this.gEndTime = gEndTime;
    }

    public int getgCommitMax() {
        return gCommitMax;
    }

    public void setgCommitMax(int gCommitMax ) {
        this.gCommitMax = gCommitMax;
    }

    public String getgPrevPanel() {
        return gPrevPanel;
    }

    public void setgPrevPanel(String gPrevPanel ) {
        this.gPrevPanel = gPrevPanel;
    }

    public String getgCheckDt() {
        return gCheckDt;
    }

    public void setgCheckDt(String gCheckDt ) {
        this.gCheckDt = gCheckDt;
    }

    public String getgPrevMenu() {
        return gPrevMenu;
    }

    public void setgPrevMenu(String gPrevMenu ) {
        this.gPrevMenu = gPrevMenu;
    }

    public String getGlobalProgramArea() {
        return globalProgramArea;
    }

    public void setGlobalProgramArea(String globalProgramArea ) {
        this.globalProgramArea = globalProgramArea;
    }

    public String getgAfdcCommArea() {
        return gAfdcCommArea;
    }

    public void setgAfdcCommArea(String gAfdcCommArea ) {
        this.gAfdcCommArea = gAfdcCommArea;
    }

    public String getgAfdcId() {
        return gAfdcId;
    }

    public void setgAfdcId(String gAfdcId ) {
        this.gAfdcId = gAfdcId;
    }

    public String getgAfdcTimeCreated() {
        return gAfdcTimeCreated;
    }

    public void setgAfdcTimeCreated(String gAfdcTimeCreated ) {
        this.gAfdcTimeCreated = gAfdcTimeCreated;
    }

    public int getgAfdcChildNbr() {
        return gAfdcChildNbr;
    }

    public void setgAfdcChildNbr(int gAfdcChildNbr ) {
        this.gAfdcChildNbr = gAfdcChildNbr;
    }

    public int getgAfdcChildPin() {
        return gAfdcChildPin;
    }

    public void setgAfdcChildPin(int gAfdcChildPin ) {
        this.gAfdcChildPin = gAfdcChildPin;
    }

    public int getgAfdcXferCases() {
        return gAfdcXferCases;
    }

    public void setgAfdcXferCases(int gAfdcXferCases ) {
        this.gAfdcXferCases = gAfdcXferCases;
    }

    public String getgAfdcUpdateFlag() {
        return gAfdcUpdateFlag;
    }

    public void setgAfdcUpdateFlag(String gAfdcUpdateFlag ) {
        this.gAfdcUpdateFlag = gAfdcUpdateFlag;
    }

    public String getgWorkerUid() {
        return gWorkerUid;
    }

    public void setgWorkerUid(String gWorkerUid ) {
        this.gWorkerUid = gWorkerUid;
    }

    public String getgChildFlg() {
        return gChildFlg;
    }

    public void setgChildFlg(String gChildFlg ) {
        this.gChildFlg = gChildFlg;
    }

    public int getgCurNbr() {
        return gCurNbr;
    }

    public void setgCurNbr(int gCurNbr ) {
        this.gCurNbr = gCurNbr;
    }

    public String getgTracDate() {
        return gTracDate;
    }

    public void setgTracDate(String gTracDate ) {
        this.gTracDate = gTracDate;
    }

    public String getgTblNbr() {
        return gTblNbr;
    }

    public void setgTblNbr(String gTblNbr ) {
        this.gTblNbr = gTblNbr;
    }

    public String getgTblName() {
        return gTblName;
    }

    public void setgTblName(String gTblName ) {
        this.gTblName = gTblName;
    }

    public String getgArgCd() {
        return gArgCd;
    }

    public void setgArgCd(String gArgCd ) {
        this.gArgCd = gArgCd;
    }

    public int getgArgLen() {
        return gArgLen;
    }

    public void setgArgLen(int gArgLen ) {
        this.gArgLen = gArgLen;
    }

    public String getgResult() {
        return gResult;
    }

    public void setgResult(String gResult ) {
        this.gResult = gResult;
    }

    public int getgResLen() {
        return gResLen;
    }

    public void setgResLen(int gResLen ) {
        this.gResLen = gResLen;
    }

    public int getgTaskId() {
        return gTaskId;
    }

    public void setgTaskId(int gTaskId ) {
        this.gTaskId = gTaskId;
    }

    public int getgEventId() {
        return gEventId;
    }

    public void setgEventId(int gEventId ) {
        this.gEventId = gEventId;
    }

    public String getgTextId() {
        return gTextId;
    }

    public void setgTextId(String gTextId ) {
        this.gTextId = gTextId;
    }

    public String getgSectionNbr() {
        return gSectionNbr;
    }

    public void setgSectionNbr(String gSectionNbr ) {
        this.gSectionNbr = gSectionNbr;
    }

    public String getgTransmittalNbr() {
        return gTransmittalNbr;
    }

    public void setgTransmittalNbr(String gTransmittalNbr ) {
        this.gTransmittalNbr = gTransmittalNbr;
    }

    public String getgReference() {
        return gReference;
    }

    public void setgReference(String gReference ) {
        this.gReference = gReference;
    }

    public int getgSubscriberId() {
        return gSubscriberId;
    }

    public void setgSubscriberId(int gSubscriberId ) {
        this.gSubscriberId = gSubscriberId;
    }

    public String getgProgramType() {
        return gProgramType;
    }

    public void setgProgramType(String gProgramType ) {
        this.gProgramType = gProgramType;
    }

    public String getgPolicyUser() {
        return gPolicyUser;
    }

    public void setgPolicyUser(String gPolicyUser ) {
        this.gPolicyUser = gPolicyUser;
    }

    public String getgApplFlag() {
        return gApplFlag;
    }

    public void setgApplFlag(String gApplFlag ) {
        this.gApplFlag = gApplFlag;
    }

    public int getgMsgNbr() {
        return gMsgNbr;
    }

    public void setgMsgNbr(int gMsgNbr ) {
        this.gMsgNbr = gMsgNbr;
    }

    public String getgText1() {
        return gText1;
    }

    public void setgText1(String gText1 ) {
        this.gText1 = gText1;
    }

    public String getgText2() {
        return gText2;
    }

    public void setgText2(String gText2 ) {
        this.gText2 = gText2;
    }

    public String getgPermSsn() {
        return gPermSsn;
    }

    public void setgPermSsn(String gPermSsn ) {
        this.gPermSsn = gPermSsn;
    }

    public String getgPermLast() {
        return gPermLast;
    }

    public void setgPermLast(String gPermLast ) {
        this.gPermLast = gPermLast;
    }

    public String getgPermFirst() {
        return gPermFirst;
    }

    public void setgPermFirst(String gPermFirst ) {
        this.gPermFirst = gPermFirst;
    }

    public String getgPermMiddle() {
        return gPermMiddle;
    }

    public void setgPermMiddle(String gPermMiddle ) {
        this.gPermMiddle = gPermMiddle;
    }

    public String getgPermMod() {
        return gPermMod;
    }

    public void setgPermMod(String gPermMod ) {
        this.gPermMod = gPermMod;
    }

    public String getgPermSex() {
        return gPermSex;
    }

    public void setgPermSex(String gPermSex ) {
        this.gPermSex = gPermSex;
    }

    public String getgPermBirthDate() {
        return gPermBirthDate;
    }

    public void setgPermBirthDate(String gPermBirthDate ) {
        this.gPermBirthDate = gPermBirthDate;
    }

    public int getgPermPin() {
        return gPermPin;
    }

    public void setgPermPin(int gPermPin ) {
        this.gPermPin = gPermPin;
    }

    public int getgPcktId() {
        return gPcktId;
    }

    public void setgPcktId(int gPcktId ) {
        this.gPcktId = gPcktId;
    }

    public String getgTime() {
        return gTime;
    }

    public void setgTime(String gTime ) {
        this.gTime = gTime;
    }

    public String getgSubject() {
        return gSubject;
    }

    public void setgSubject(String gSubject ) {
        this.gSubject = gSubject;
    }

    public String getgLastName() {
        return gLastName;
    }

    public void setgLastName(String gLastName ) {
        this.gLastName = gLastName;
    }

    public int getGcsCaseId() {
        return gcsCaseId;
    }

    public void setGcsCaseId(int gcsCaseId ) {
        this.gcsCaseId = gcsCaseId;
    }

    public String getgEnforce() {
        return gEnforce;
    }

    public void setgEnforce(String gEnforce ) {
        this.gEnforce = gEnforce;
    }

    public String getgHearingDt() {
        return gHearingDt;
    }

    public void setgHearingDt(String gHearingDt ) {
        this.gHearingDt = gHearingDt;
    }

    public String getgHearingTime() {
        return gHearingTime;
    }

    public void setgHearingTime(String gHearingTime ) {
        this.gHearingTime = gHearingTime;
    }

    public String getgCan() {
        return gCan;
    }

    public void setgCan(String gCan ) {
        this.gCan = gCan;
    }

    public String getgCanCountyCd() {
        return gCanCountyCd;
    }

    public void setgCanCountyCd(String gCanCountyCd ) {
        this.gCanCountyCd = gCanCountyCd;
    }

    public String getgCanStatus() {
        return gCanStatus;
    }

    public void setgCanStatus(String gCanStatus ) {
        this.gCanStatus = gCanStatus;
    }

    public String getgJudgeFlmId() {
        return gJudgeFlmId;
    }

    public void setgJudgeFlmId(String gJudgeFlmId ) {
        this.gJudgeFlmId = gJudgeFlmId;
    }

    public String getgJudgeFlmType() {
        return gJudgeFlmType;
    }

    public void setgJudgeFlmType(String gJudgeFlmType ) {
        this.gJudgeFlmType = gJudgeFlmType;
    }

    public String getgCourtType() {
        return gCourtType;
    }

    public void setgCourtType(String gCourtType ) {
        this.gCourtType = gCourtType;
    }

    public String getgOosDocketNbr() {
        return gOosDocketNbr;
    }

    public void setgOosDocketNbr(String gOosDocketNbr ) {
        this.gOosDocketNbr = gOosDocketNbr;
    }

    public String getgTempOrdrFlag() {
        return gTempOrdrFlag;
    }

    public void setgTempOrdrFlag(String gTempOrdrFlag ) {
        this.gTempOrdrFlag = gTempOrdrFlag;
    }

    public int getgPageNo() {
        return gPageNo;
    }

    public void setgPageNo(int gPageNo ) {
        this.gPageNo = gPageNo;
    }

    public String getgCaptionFlag() {
        return gCaptionFlag;
    }

    public void setgCaptionFlag(String gCaptionFlag ) {
        this.gCaptionFlag = gCaptionFlag;
    }

    public String getgProgramArea1() {
        return gProgramArea1;
    }

    public void setgProgramArea1(String gProgramArea1 ) {
        this.gProgramArea1 = gProgramArea1;
    }

    public String getgProgramArea2() {
        return gProgramArea2;
    }

    public void setgProgramArea2(String gProgramArea2 ) {
        this.gProgramArea2 = gProgramArea2;
    }

    public String getgRoleId() {
        return gRoleId;
    }

    public void setgRoleId(String gRoleId ) {
        this.gRoleId = gRoleId;
    }

    public String getgRegion() {
        return gRegion;
    }

    public void setgRegion(String gRegion ) {
        this.gRegion = gRegion;
    }

    public int getgInvsId() {
        return gInvsId;
    }

    public void setgInvsId(int gInvsId ) {
        this.gInvsId = gInvsId;
    }

    public String getgApptUid() {
        return gApptUid;
    }

    public void setgApptUid(String gApptUid ) {
        this.gApptUid = gApptUid;
    }

    public String getgForm() {
        return gForm;
    }

    public void setgForm(String gForm ) {
        this.gForm = gForm;
    }

    public String getgForm1() {
        return gForm1;
    }

    public void setgForm1(String gForm1 ) {
        this.gForm1 = gForm1;
    }

    public String getgFqt() {
        return gFqt;
    }

    public void setgFqt(String gFqt ) {
        this.gFqt = gFqt;
    }

    public int getgQCnt() {
        return gQCnt;
    }

    public void setgQCnt(int gQCnt ) {
        this.gQCnt = gQCnt;
    }

    public String getgFormFlag() {
        return gFormFlag;
    }

    public void setgFormFlag(String gFormFlag ) {
        this.gFormFlag = gFormFlag;
    }

    public String getgFormTimestamp() {
        return gFormTimestamp;
    }

    public void setgFormTimestamp(String gFormTimestamp ) {
        this.gFormTimestamp = gFormTimestamp;
    }

    public int getgAssetId() {
        return gAssetId;
    }

    public void setgAssetId(int gAssetId ) {
        this.gAssetId = gAssetId;
    }

    public String getgCanMultiDef() {
        return gCanMultiDef;
    }

    public void setgCanMultiDef(String gCanMultiDef ) {
        this.gCanMultiDef = gCanMultiDef;
    }

    public int getgMultiDefCaseId() {
        return gMultiDefCaseId;
    }

    public void setgMultiDefCaseId(int gMultiDefCaseId ) {
        this.gMultiDefCaseId = gMultiDefCaseId;
    }

    @Override
    public String toString() {
        return "Weo0g000 [gApId =" + gApId + " ,gApSsn =" + gApSsn + " ,gApName =" + gApName + " ,gApLast =" + gApLast + " ,gApFirst =" + gApFirst + " ,gApMi =" + gApMi + " ,gApMod =" + gApMod + " ,gApPin =" + gApPin + " ,gFipsNbr =" + gFipsNbr + " ,gCountyCd =" + gCountyCd + " ,gCaseload =" + gCaseload + " ,gCaseId =" + gCaseId + " ,gCaseNbr =" + gCaseNbr + " ,gCaseType =" + gCaseType + " ,gOosCaseType =" + gOosCaseType + " ,gCtId =" + gCtId + " ,gCtSsn =" + gCtSsn + " ,gCtName =" + gCtName + " ,gCtLast =" + gCtLast + " ,gCtFirst =" + gCtFirst + " ,gCtMi =" + gCtMi + " ,gCtMod =" + gCtMod + " ,gCtPin =" + gCtPin + " ,gApplicantId =" + gApplicantId + " ,gEnv =" + gEnv + " ,gSqlid =" + gSqlid + " ,gAttr =" + gAttr + " ,gPopMode =" + gPopMode + " ,gValidated =" + gValidated + " ,gTitle =" + gTitle + " ,gSubtitle =" + gSubtitle + " ,gProgram =" + gProgram + " ,gPanel =" + gPanel + " ,gStackedData =" + gStackedData + "  ,gStackedMode =" + gStackedMode + " ,gStackedPanel =" + gStackedPanel + " ,gStackedPin =" + gStackedPin + " ,gCv =" + gCv + " ,gCommand =" + gCommand + " ,gUpdatable =" + gUpdatable + " ,gSqlstmt =" + gSqlstmt + " ,gSqlstmtl =" + gSqlstmtl + " ,gSqlca =" + gSqlca + " ,gSqlcaid =" + gSqlcaid + " ,gSqlcabc =" + gSqlcabc + " ,gSqlcode =" + gSqlcode + " ,gSqlerrml =" + gSqlerrml + " ,gSqlerrm =" + gSqlerrm + " ,gSqlerrp =" + gSqlerrp + " ,gSqlerrd =" + gSqlerrd + " ,gSqlwarn0 =" + gSqlwarn0 + " ,gSqlwarn1 =" + gSqlwarn1 + " ,gSqlwarn2 =" + gSqlwarn2 + " ,gSqlwarn3 =" + gSqlwarn3 + " ,gSqlwarn4 =" + gSqlwarn4 + " ,gSqlwarn5 =" + gSqlwarn5 + " ,gSqlwarn6 =" + gSqlwarn6 + " ,gSqlwarn7 =" + gSqlwarn7 + " ,gSqlext =" + gSqlext + " ,gRc =" + gRc + " ,gTodaysDt =" + gTodaysDt + " ,gPeriodDt =" + gPeriodDt + " ,gBatchNbr =" + gBatchNbr + " ,gCheckNbr =" + gCheckNbr + " ,gClaimNumber =" + gClaimNumber + " ,gReceiptId =" + gReceiptId + " ,gFromDate =" + gFromDate + " ,gCommitData =" + gCommitData + " ,gStartTime =" + gStartTime + " ,gEndTime =" + gEndTime + " ,gCommitMax =" + gCommitMax + " ,gPrevPanel =" + gPrevPanel + " ,gCheckDt =" + gCheckDt + " ,gPrevMenu =" + gPrevMenu + " ,globalProgramArea =" + globalProgramArea + " ,gAfdcCommArea =" + gAfdcCommArea + " ,gAfdcId =" + gAfdcId + " ,gAfdcTimeCreated =" + gAfdcTimeCreated + " ,gAfdcChildNbr =" + gAfdcChildNbr + " ,gAfdcChildPin =" + gAfdcChildPin + " ,gAfdcXferCases =" + gAfdcXferCases + " ,gAfdcUpdateFlag =" + gAfdcUpdateFlag + " ,gWorkerUid =" + gWorkerUid + " ,gChildFlg =" + gChildFlg + " ,gCurNbr =" + gCurNbr + " ,gTracDate =" + gTracDate + " ,gTblNbr =" + gTblNbr + " ,gTblName =" + gTblName + " ,gArgCd =" + gArgCd + " ,gArgLen =" + gArgLen + " ,gResult =" + gResult + " ,gResLen =" + gResLen + " ,gTaskId =" + gTaskId + " ,gEventId =" + gEventId + " ,gTextId =" + gTextId + " ,gSectionNbr =" + gSectionNbr + " ,gTransmittalNbr =" + gTransmittalNbr + " ,gReference =" + gReference + " ,gSubscriberId =" + gSubscriberId + " ,gProgramType =" + gProgramType + " ,gPolicyUser =" + gPolicyUser + " ,gApplFlag =" + gApplFlag + " ,gMsgNbr =" + gMsgNbr + " ,gText1 =" + gText1 + " ,gText2 =" + gText2 + " ,gPermSsn =" + gPermSsn + " ,gPermLast =" + gPermLast + " ,gPermFirst =" + gPermFirst + " ,gPermMiddle =" + gPermMiddle + " ,gPermMod =" + gPermMod + " ,gPermSex =" + gPermSex + " ,gPermBirthDate =" + gPermBirthDate + " ,gPermPin =" + gPermPin + " ,gPcktId =" + gPcktId + " ,gTime =" + gTime + " ,gSubject =" + gSubject + " ,gLastName =" + gLastName + " ,gcsCaseId =" + gcsCaseId + " ,gEnforce =" + gEnforce + " ,gHearingDt =" + gHearingDt + " ,gHearingTime =" + gHearingTime + " ,gCan =" + gCan + " ,gCanCountyCd =" + gCanCountyCd + " ,gCanStatus =" + gCanStatus + " ,gJudgeFlmId =" + gJudgeFlmId + " ,gJudgeFlmType =" + gJudgeFlmType + " ,gCourtType =" + gCourtType + " ,gOosDocketNbr =" + gOosDocketNbr + " ,gTempOrdrFlag =" + gTempOrdrFlag + " ,gPageNo =" + gPageNo + " ,gCaptionFlag =" + gCaptionFlag + " ,gProgramArea1 =" + gProgramArea1 + " ,gProgramArea2 =" + gProgramArea2 + " ,gRoleId =" + gRoleId + " ,gRegion =" + gRegion + " ,gInvsId =" + gInvsId + " ,gApptUid =" + gApptUid + " ,gForm =" + gForm + " ,gForm1 =" + gForm1 + " ,gFqt =" + gFqt + " ,gQCnt =" + gQCnt + " ,gFormFlag =" + gFormFlag + " ,gFormTimestamp =" + gFormTimestamp + " ,gAssetId =" + gAssetId + " ,gCanMultiDef =" + gCanMultiDef + " ,gMultiDefCaseId =" + gMultiDefCaseId+ "]";
    }
}