package com.swv.oscar.dataobject.common;

import java.io.Serializable;

/*************************************************************************
 *
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2017 HCL. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0rcnl implements Serializable {

    private String choice;
    private String opt;
    private String gStackedPanel;
    private String gStackedMode;
    private String gCtId;
    private String gApPin;
    private String gCtPin;
    private String gApId;
    private String gCountyCd;
    private String gApName;
    private String gCtName;
    private String gCaseload;
    private String gCaseType;
    private String gOosCaseType;
    private String gApplicantId;
    private String gCurNbr;
    private String gText1;
    private String gApplFlag;
    private String gCommand;
    public String getChoice() {
        return choice;
    }

    public void setChoice(String choice ) {
        this.choice = choice;
    }

    public String getOpt() {
        return opt;
    }

    public void setOpt(String opt ) {
        this.opt = opt;
    }

    public String getgStackedPanel() {
        return gStackedPanel;
    }

    public void setgStackedPanel(String gStackedPanel ) {
        this.gStackedPanel = gStackedPanel;
    }

    public String getgStackedMode() {
        return gStackedMode;
    }

    public void setgStackedMode(String gStackedMode ) {
        this.gStackedMode = gStackedMode;
    }

    public String getgCtId() {
        return gCtId;
    }

    public void setgCtId(String gCtId ) {
        this.gCtId = gCtId;
    }

    public String getgApPin() {
        return gApPin;
    }

    public void setgApPin(String gApPin ) {
        this.gApPin = gApPin;
    }

    public String getgCtPin() {
        return gCtPin;
    }

    public void setgCtPin(String gCtPin ) {
        this.gCtPin = gCtPin;
    }

    public String getgApId() {
        return gApId;
    }

    public void setgApId(String gApId ) {
        this.gApId = gApId;
    }

    public String getgCountyCd() {
        return gCountyCd;
    }

    public void setgCountyCd(String gCountyCd ) {
        this.gCountyCd = gCountyCd;
    }

    public String getgApName() {
        return gApName;
    }

    public void setgApName(String gApName ) {
        this.gApName = gApName;
    }

    public String getgCtName() {
        return gCtName;
    }

    public void setgCtName(String gCtName ) {
        this.gCtName = gCtName;
    }

    public String getgCaseload() {
        return gCaseload;
    }

    public void setgCaseload(String gCaseload ) {
        this.gCaseload = gCaseload;
    }

    public String getgCaseType() {
        return gCaseType;
    }

    public void setgCaseType(String gCaseType ) {
        this.gCaseType = gCaseType;
    }

    public String getgOosCaseType() {
        return gOosCaseType;
    }

    public void setgOosCaseType(String gOosCaseType ) {
        this.gOosCaseType = gOosCaseType;
    }

    public String getgApplicantId() {
        return gApplicantId;
    }

    public void setgApplicantId(String gApplicantId ) {
        this.gApplicantId = gApplicantId;
    }

    public String getgCurNbr() {
        return gCurNbr;
    }

    public void setgCurNbr(String gCurNbr ) {
        this.gCurNbr = gCurNbr;
    }

    public String getgText1() {
        return gText1;
    }

    public void setgText1(String gText1 ) {
        this.gText1 = gText1;
    }

    public String getgApplFlag() {
        return gApplFlag;
    }

    public void setgApplFlag(String gApplFlag ) {
        this.gApplFlag = gApplFlag;
    }

    public String getgCommand() {
        return gCommand;
    }

    public void setgCommand(String gCommand ) {
        this.gCommand = gCommand;
    }

    @Override
    public String toString() {
        return "Weo0rcnl [choice =" + choice + " ,opt =" + opt + " ,gStackedPanel =" + gStackedPanel + " ,gStackedMode =" + gStackedMode + " ,gCtId =" + gCtId + " ,gApPin =" + gApPin + " ,gCtPin =" + gCtPin + " ,gApId =" + gApId + " ,gCountyCd =" + gCountyCd + " ,gApName =" + gApName + " ,gCtName =" + gCtName + " ,gCaseload =" + gCaseload + " ,gCaseType =" + gCaseType + " ,gOosCaseType =" + gOosCaseType + " ,gApplicantId =" + gApplicantId + " ,gCurNbr =" + gCurNbr + " ,gText1 =" + gText1 + " ,gApplFlag =" + gApplFlag + " ,gCommand =" + gCommand+ "]";
    }
}