package com.swv.oscar.dataobject.common;

import java.io.Serializable;
import java.util.List;

/*************************************************************************
 *
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * HCL is a trademark of HCL Company.
 *
 * Copyright © 2017 HCL. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0rcnlBO extends BaseBO implements Serializable {

    private List<Weo0rcnl> weo0rcnl;
    public List<Weo0rcnl> getWeo0rcnl() {
        return weo0rcnl;
    }

    public void setWeo0rcnl(List<Weo0rcnl> weo0rcnl ) {
        this.weo0rcnl = weo0rcnl;
    }

    @Override
    public String toString() {
        return "Weo0rcnlBO [weo0rcnl =" + weo0rcnl+ "]";
    }
}