package com.swv.oscar.dataobject.common;

import java.io.Serializable;
import java.util.List;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 * Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0nctsBO extends BaseBO implements Serializable {

    private List<Weo0ncts> weo0ncts;
    public List<Weo0ncts> getWeo0ncts() {
        return weo0ncts;
    }

    public void setWeo0ncts(List<Weo0ncts> weo0ncts ) {
        this.weo0ncts = weo0ncts;
    }

    @Override
    public String toString() {
        return "Weo0nctsBO [weo0ncts =" + weo0ncts+ "]";
    }
}