package com.swv.oscar.dataobject.batch;

import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;

/*************************************************************************
 *
 * OSCAR CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * OSCAR is a trademark of OSCAR Company.
 *
 * Copyright © 2017 OSCAR. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of OSCAR
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to OSCAR and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from OSCAR.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public  class Trigger implements Serializable {

    private String recordType;
    private int recordId;
    private String updateType;
    private String timeCreated;
    private String uidCreated;
    public String getRecordType() {
        return recordType;
    }

    public void setRecordType(String recordType ) {
        this.recordType = recordType;
    }

    public int getRecordId() {
        return recordId;
    }

    public void setRecordId(int recordId ) {
        this.recordId = recordId;
    }

    public String getUpdateType() {
        return updateType;
    }

    public void setUpdateType(String updateType ) {
        this.updateType = updateType;
    }

    public String getTimeCreated() {
        return timeCreated;
    }

    public void setTimeCreated(String timeCreated ) {
        this.timeCreated = timeCreated;
    }

    public String getUidCreated() {
        return uidCreated;
    }

    public void setUidCreated(String uidCreated ) {
        this.uidCreated = uidCreated;
    }

 //   @Override
  /*  public String toString() {
       // return "Trigger [VarDefContext [accessSpecifiers=null, keyword=null, dataType=String, varName=recordType, value=null] =" + VarDefContext [accessSpecifiers=null, keyword=null, dataType=String, varName=recordType, value=null] + "VarDefContext [accessSpecifiers=null, keyword=null, dataType=int, varName=recordId, value=null] =" + VarDefContext [accessSpecifiers=null, keyword=null, dataType=int, varName=recordId, value=null] + " ,VarDefContext [accessSpecifiers=null, keyword=null, dataType=String, varName=updateType, value=null] =" + VarDefContext [accessSpecifiers=null, keyword=null, dataType=String, varName=updateType, value=null] + " ,VarDefContext [accessSpecifiers=null, keyword=null, dataType=String, varName=timeCreated, value=null] =" + VarDefContext [accessSpecifiers=null, keyword=null, dataType=String, varName=timeCreated, value=null] + " ,VarDefContext [accessSpecifiers=null, keyword=null, dataType=String, varName=uidCreated, value=null] =" + VarDefContext [accessSpecifiers=null, keyword=null, dataType=String, varName=uidCreated, value=null]+ "]";
    }*/
}