package com.swv.oscar.dataobject.batch;

import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;

/*************************************************************************
 *
 * OSCAR CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * OSCAR is a trademark of OSCAR Company.
 *
 * Copyright © 2017 OSCAR. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of OSCAR
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to OSCAR and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from OSCAR.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0nenv   implements Serializable {

    private String env;
    private int rc;
    private String fname;
    private String dbt;
   // private 1 0;
    private String fnrt;
    private String hname;
    private int qty;
    private int i;
    private String applicId;
    public String getEnv() {
        return env;
    }

    public void setEnv(String env ) {
        this.env = env;
    }

    public int getRc() {
        return rc;
    }

    public void setRc(int rc ) {
        this.rc = rc;
    }

    public String getFname() {
        return fname;
    }

    public void setFname(String fname ) {
        this.fname = fname;
    }

    public String getDbt() {
        return dbt;
    }

    public void setDbt(String dbt ) {
        this.dbt = dbt;
    }

   // public 1 get0() {
   //     return 0;
  //  }

 //   public void set0(1 0 ) {
  //      this.0 = 0;
  //  }

    public String getFnrt() {
        return fnrt;
    }

    public void setFnrt(String fnrt ) {
        this.fnrt = fnrt;
    }

    public String getHname() {
        return hname;
    }

    public void setHname(String hname ) {
        this.hname = hname;
    }

    public int getQty() {
        return qty;
    }

    public void setQty(int qty ) {
        this.qty = qty;
    }

    public int getI() {
        return i;
    }

    public void setI(int i ) {
        this.i = i;
    }

    public String getApplicId() {
        return applicId;
    }

    public void setApplicId(String applicId ) {
        this.applicId = applicId;
    }

    @Override
    public String toString() {
        return "Weo0nenv [env =" + env + " ,rc =" + rc + " ,fname =" + fname + " ,dbt =" + dbt + " ,0 =" + 0 + " ,fnrt =" + fnrt + " ,hname =" + hname + " ,qty =" + qty + " ,i =" + i + " ,applicId =" + applicId+ "]";
    }
}