package com.swv.oscar.dataobject.batch;

import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;

/*************************************************************************
 *
 * OSCAR CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * OSCAR is a trademark of OSCAR Company.
 *
 * Copyright © 2017 OSCAR. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of OSCAR
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to OSCAR and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from OSCAR.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0perr   implements Serializable {

    private String opt;
    private String choice;
    private String sqlext;
    private String sqlwarn8;
    private String sqlwarn9;
    private String sqlwarna;
    private String sqlstate;
    private String errorLvl;
    private String errornr;
    private String errorLn;
    private String errorPgm;
    private String errorO;
    private String natdb2Rc;
    private String natdb2Reason;
    private String errText;
    private String line;
    private String errorText;
    private String lrecl;
    public String getOpt() {
        return opt;
    }

    public void setOpt(String opt ) {
        this.opt = opt;
    }

    public String getChoice() {
        return choice;
    }

    public void setChoice(String choice ) {
        this.choice = choice;
    }

    public String getSqlext() {
        return sqlext;
    }

    public void setSqlext(String sqlext ) {
        this.sqlext = sqlext;
    }

    public String getSqlwarn8() {
        return sqlwarn8;
    }

    public void setSqlwarn8(String sqlwarn8 ) {
        this.sqlwarn8 = sqlwarn8;
    }

    public String getSqlwarn9() {
        return sqlwarn9;
    }

    public void setSqlwarn9(String sqlwarn9 ) {
        this.sqlwarn9 = sqlwarn9;
    }

    public String getSqlwarna() {
        return sqlwarna;
    }

    public void setSqlwarna(String sqlwarna ) {
        this.sqlwarna = sqlwarna;
    }

    public String getSqlstate() {
        return sqlstate;
    }

    public void setSqlstate(String sqlstate ) {
        this.sqlstate = sqlstate;
    }

    public String getErrorLvl() {
        return errorLvl;
    }

    public void setErrorLvl(String errorLvl ) {
        this.errorLvl = errorLvl;
    }

    public String getErrornr() {
        return errornr;
    }

    public void setErrornr(String errornr ) {
        this.errornr = errornr;
    }

    public String getErrorLn() {
        return errorLn;
    }

    public void setErrorLn(String errorLn ) {
        this.errorLn = errorLn;
    }

    public String getErrorPgm() {
        return errorPgm;
    }

    public void setErrorPgm(String errorPgm ) {
        this.errorPgm = errorPgm;
    }

    public String getErrorO() {
        return errorO;
    }

    public void setErrorO(String errorO ) {
        this.errorO = errorO;
    }

    public String getNatdb2Rc() {
        return natdb2Rc;
    }

    public void setNatdb2Rc(String natdb2Rc ) {
        this.natdb2Rc = natdb2Rc;
    }

    public String getNatdb2Reason() {
        return natdb2Reason;
    }

    public void setNatdb2Reason(String natdb2Reason ) {
        this.natdb2Reason = natdb2Reason;
    }

    public String getErrText() {
        return errText;
    }

    public void setErrText(String errText ) {
        this.errText = errText;
    }

    public String getLine() {
        return line;
    }

    public void setLine(String line ) {
        this.line = line;
    }

    public String getErrorText() {
        return errorText;
    }

    public void setErrorText(String errorText ) {
        this.errorText = errorText;
    }

    public String getLrecl() {
        return lrecl;
    }

    public void setLrecl(String lrecl ) {
        this.lrecl = lrecl;
    }

    @Override
    public String toString() {
        return "Weo0perr [opt =" + opt + " ,choice =" + choice + " ,sqlext =" + sqlext + " ,sqlwarn8 =" + sqlwarn8 + " ,sqlwarn9 =" + sqlwarn9 + " ,sqlwarna =" + sqlwarna + " ,sqlstate =" + sqlstate + " ,errorLvl =" + errorLvl + " ,errornr =" + errornr + " ,errorLn =" + errorLn + " ,errorPgm =" + errorPgm + " ,errorO =" + errorO + " ,natdb2Rc =" + natdb2Rc + " ,natdb2Reason =" + natdb2Reason + " ,errText =" + errText + " ,line =" + line + " ,errorText =" + errorText + " ,lrecl =" + lrecl+ "]";
    }
}