package com.swv.oscar.dataobject.batch;

import java.io.Serializable;
import java.util.List;

import com.swv.oscar.dataobject.common.BaseBO;

import java.util.ArrayList;

/*************************************************************************
 *
 * OSCAR CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * OSCAR is a trademark of OSCAR Company.
 *
 * Copyright © 2017 OSCAR. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of OSCAR
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to OSCAR and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from OSCAR.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0crptBO extends BaseBO implements Serializable {


    private List<Weo0crpt> weo0crpt;
    private int exeStatus;
    public List<Weo0crpt> getWeo0crpt() {
        if(weo0crpt == null) {
            weo0crpt = new ArrayList<Weo0crpt>();
        }
        return weo0crpt;
    }

    public void setWeo0crpt(List<Weo0crpt> weo0crpt ) {
        this.weo0crpt = weo0crpt;
    }

    public int getExeStatus() {
        return exeStatus;
    }

    public void setExeStatus(int exeStatus ) {
        this.exeStatus = exeStatus;
    }

    @Override
    public String toString() {
        return "Weo0crptBO [weo0crpt =" + weo0crpt + " ,exeStatus =" + exeStatus+ "]";
    }
}