package com.swv.oscar.dataobject.batch;

import java.io.Serializable;
import java.util.List;

import com.swv.oscar.dataobject.common.BaseBO;

import java.util.ArrayList;

/*************************************************************************
 *
 * OSCAR CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * OSCAR is a trademark of OSCAR Company.
 *
 * Copyright © 2017 OSCAR. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of OSCAR
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to OSCAR and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from OSCAR.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo0mrstBO extends BaseBO implements Serializable {


    private List<Weo0mrst> weo0mrst;
    private int exeStatus;
    public List<Weo0mrst> getWeo0mrst() {
        if(weo0mrst == null) {
            weo0mrst = new ArrayList<Weo0mrst>();
        }
        return weo0mrst;
    }

    public void setWeo0mrst(List<Weo0mrst> weo0mrst ) {
        this.weo0mrst = weo0mrst;
    }

    public int getExeStatus() {
        return exeStatus;
    }

    public void setExeStatus(int exeStatus ) {
        this.exeStatus = exeStatus;
    }

    @Override
    public String toString() {
        return "Weo0mrstBO [weo0mrst =" + weo0mrst + " ,exeStatus =" + exeStatus+ "]";
    }
}