package com.swv.oscar.dataobject.batch;
import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;

/*************************************************************************
 *
 * OSCAR CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * OSCAR is a trademark of OSCAR Company.
 *
 * Copyright © 2017 OSCAR. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of OSCAR
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to OSCAR and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from OSCAR.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo2nsrv   implements Serializable {

    private String to;
    private String screen;
    private String input;
    private String callPgm;
    private String time;
    private int caseId;
    private String otherData;
    private String oldValue;
    private String newValue;
    private String next30;
    private String task;
    private String rc;
    private String alEvent;
    private String text1;
    private String weo2nsrvTo;
    private String weo2nsrvScreen;
    private String old;
   // private String new;
    private Vcasetr vcasetr;
    public String getTo() {
        return to;
    }

    public void setTo(String to ) {
        this.to = to;
    }

    public String getScreen() {
        return screen;
    }

    public void setScreen(String screen ) {
        this.screen = screen;
    }

    public String getInput() {
        return input;
    }

    public void setInput(String input ) {
        this.input = input;
    }

    public String getCallPgm() {
        return callPgm;
    }

    public void setCallPgm(String callPgm ) {
        this.callPgm = callPgm;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time ) {
        this.time = time;
    }

    public int getCaseId() {
        return caseId;
    }

    public void setCaseId(int caseId ) {
        this.caseId = caseId;
    }

    public String getOtherData() {
        return otherData;
    }

    public void setOtherData(String otherData ) {
        this.otherData = otherData;
    }

    public String getOldValue() {
        return oldValue;
    }

    public void setOldValue(String oldValue ) {
        this.oldValue = oldValue;
    }

    public String getNewValue() {
        return newValue;
    }

    public void setNewValue(String newValue ) {
        this.newValue = newValue;
    }

    public String getNext30() {
        return next30;
    }

    public void setNext30(String next30 ) {
        this.next30 = next30;
    }

    public String getTask() {
        return task;
    }

    public void setTask(String task ) {
        this.task = task;
    }

    public String getRc() {
        return rc;
    }

    public void setRc(String rc ) {
        this.rc = rc;
    }

    public String getAlEvent() {
        return alEvent;
    }

    public void setAlEvent(String alEvent ) {
        this.alEvent = alEvent;
    }

    public String getText1() {
        return text1;
    }

    public void setText1(String text1 ) {
        this.text1 = text1;
    }

    public String getWeo2nsrvTo() {
        return weo2nsrvTo;
    }

    public void setWeo2nsrvTo(String weo2nsrvTo ) {
        this.weo2nsrvTo = weo2nsrvTo;
    }

    public String getWeo2nsrvScreen() {
        return weo2nsrvScreen;
    }

    public void setWeo2nsrvScreen(String weo2nsrvScreen ) {
        this.weo2nsrvScreen = weo2nsrvScreen;
    }

    public String getOld() {
        return old;
    }

    public void setOld(String old ) {
        this.old = old;
    }

    /*public String getNew() {
        return new;
    }

    public void setNew(String new ) {
        this.new = new;
    }*/

    public Vcasetr getVcasetr() {
        return vcasetr;
    }

    public void setVcasetr(Vcasetr vcasetr ) {
        this.vcasetr = vcasetr;
    }

  /*  @Override
    public String toString() {
        return "Weo2nsrv [to =" + to + " ,screen =" + screen + " ,input =" + input + " ,callPgm =" + callPgm + " ,time =" + time + " ,caseId =" + caseId + " ,otherData =" + otherData + " ,oldValue =" + oldValue + " ,newValue =" + newValue + " ,next30 =" + next30 + " ,task =" + task + " ,rc =" + rc + " ,alEvent =" + alEvent + " ,text1 =" + text1 + " ,weo2nsrvTo =" + weo2nsrvTo + " ,weo2nsrvScreen =" + weo2nsrvScreen + " ,old =" + old + " ,new =" + new + " ,vcasetr =" + vcasetr+ "]";
    }*/
}