package com.oscar.swv.dataobject;

import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;

/*************************************************************************
 *
 * OSCAR CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * OSCAR is a trademark of OSCAR Company.
 *
 * Copyright © 2017 OSCAR. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of OSCAR
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to OSCAR and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from OSCAR.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo5sfcd   implements Serializable {

    private String pUpdateType;
    private String timeCreated;
    private Vcasetr vcasetr;
    private Trigger trigger;
    public String getpUpdateType() {
        return pUpdateType;
    }

    public void setpUpdateType(String pUpdateType ) {
        this.pUpdateType = pUpdateType;
    }

    public String getTimeCreated() {
        return timeCreated;
    }

    public void setTimeCreated(String timeCreated ) {
        this.timeCreated = timeCreated;
    }

    public Vcasetr getVcasetr() {
        return vcasetr;
    }

    public void setVcasetr(Vcasetr vcasetr ) {
        this.vcasetr = vcasetr;
    }

    public Trigger getTrigger() {
        return trigger;
    }

    public void setTrigger(Trigger trigger ) {
        this.trigger = trigger;
    }

    @Override
    public String toString() {
        return "Weo5sfcd [pUpdateType =" + pUpdateType + " ,timeCreated =" + timeCreated + " ,vcasetr =" + vcasetr + " ,trigger =" + trigger+ "]";
    }
}