package com.oscar.swv.dataobject;

import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;

/*************************************************************************
 *
 * OSCAR CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * OSCAR is a trademark of OSCAR Company.
 *
 * Copyright © 2017 OSCAR. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of OSCAR
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to OSCAR and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from OSCAR.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo5sfv1BO extends BaseBO implements Serializable {


    private List<Weo5sfv1> weo5sfv1;
    private int exeStatus;
    public List<Weo5sfv1> getWeo5sfv1() {
        if(weo5sfv1 == null) {
            weo5sfv1 = new ArrayList<Weo5sfv1>();
        }
        return weo5sfv1;
    }

    public void setWeo5sfv1(List<Weo5sfv1> weo5sfv1 ) {
        this.weo5sfv1 = weo5sfv1;
    }

    public int getExeStatus() {
        return exeStatus;
    }

    public void setExeStatus(int exeStatus ) {
        this.exeStatus = exeStatus;
    }

    @Override
    public String toString() {
        return "Weo5sfv1BO [weo5sfv1 =" + weo5sfv1 + " ,exeStatus =" + exeStatus+ "]";
    }
}