package com.oscar.swv.dataobject;

import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;

/*************************************************************************
 *
 * OSCAR CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * OSCAR is a trademark of OSCAR Company.
 *
 * Copyright © 2017 OSCAR. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of OSCAR
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to OSCAR and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from OSCAR.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo5sdly   implements Serializable {

    private String 1;
    private String 0030;
    private String toKeylineFmt;
    private String 0040;
    private String formId;
    private String 0050;
    private String pcktId;
    private String 0060;
    private String state;
    private String 0070;
    private String county;
    private String 0080;
    private String civActNbr;
    private String 0090;
    private String empFein;
    private String 0100;
    private String employer;
    private String 0110;
    private String empAdd1;
    private String 0120;
    private String empAdd2;
    private String 0130;
    private String empAdd3;
    private String 0140;
    private String empCity;
    private String 0150;
    private String empState;
    private String 0160;
    private String empZip;
    private String 0170;
    private String empCountryName;
    private String 0180;
    private String apLast;
    private String 0190;
    private String apFirst;
    private String 0200;
    private String apMid;
    private String 0210;
    private String apMod;
    private String 0220;
    private String apSsn;
    private String 0230;
    private String caseNbr1;
    private String 0240;
    private String ctLast;
    private String 0250;
    private String ctFirst;
    private String 0260;
    private String ctMid;
    private String 0270;
    private String ctMod;
    private String 0280;
    private String oblgAmt;
    private String 20290;
    private String csFreq;
    private String 0300;
    private String arrears;
    private String 20310;
    private String pastCsFreq;
    private String 0320;
    private String arrears12wks;
    private String 0330;
    private String medical;
    private String 20340;
    private String medFreq;
    private String 0350;
    private String pastMedical;
    private String 20360;
    private String pastMedFreq;
    private String 0370;
    private String spousal;
    private String 20380;
    private String spousalFreq;
    private String 0390;
    private String pastSpousal;
    private String 20400;
    private String pastSpousalFreq;
    private String 0410;
    private String totalAmt;
    private String 20420;
    private String weeklyPay;
    private String 20430;
    private String biweeklyPay;
    private String 20440;
    private String semimnthPay;
    private String 20450;
    private String agencyPayee;
    private String 0460;
    private String payeeAdd1;
    private String 0470;
    private String payeeAdd2;
    private String 0480;
    private String payeeCity;
    private String 0490;
    private String payeeState;
    private String 0500;
    private String payeeZip;
    private String 0510;
    private String payeeFipsCode;
    private String 0520;
    private String workerName;
    private String 0530;
    private String docDate;
    private String 0540;
    private String otherDue;
    private String 20550;
    private String otherDueFreq;
    private String 0560;
    private String otherDueDesc;
    private String 0570;
    private String addInfo1;
    private String 0580;
    private String addInfo2;
    private String 0590;
    private String addInfo3;
    private String 0600;
    private String childArray;
    private String 0620;
    private String phoneExtn;
    private String 0630;
    private String faxNbr;
    private String 0640;
    private String workerEmail;
    private String 0650;
    private String formPrinted;
    private String 0660;
    private String formType;
    private String 0670;
    private String wrkrUid;
    private String 0680;
    private String timeStamp;
    private String 0690;
    private String caseId;
    private String 0700;
    private String apAdd1;
    private String 0710;
    private String apAdd2;
    private String 0720;
    private String apAdd3;
    private String 0730;
    private String apCity;
    private String 0740;
    private String apState;
    private String 0750;
    private String apZip;
    private String 0760;
    private String apCountry;
    private String 0770;
    private String ctAdd1;
    private String 0780;
    private String ctAdd2;
    private String 0790;
    private String ctAdd3;
    private String 0800;
    private String ctCity;
    private String 0810;
    private String ctState;
    private String 0820;
    private String ctZip;
    private String 0830;
    private String ctCountry;
    private String 0840;
    private String wrkrAdd1;
    private String 0850;
    private String wrkrAdd2;
    private String 0860;
    private String wrkrCity;
    private String 0870;
    private String wrkrState;
    private String 0880;
    private String wrkrZip;
    private String 0890;
    private String uidCreated;
    private String 0900;
    private String oblgState;
    private String 0910;
    private String bankRouting;
    private String 0920;
    private String bankAccount;
    private String 0930;
    private String envInd;
    private String 0940;
    private String emprUnit;
    private String 0950;
    private String emprPhone;
    private String 0960;
    private String emprFax;
    private String 0970;
    private String lumpSumAmt;
    private String 20980;
    private String telephone1;
    private String 0990;
    private String telephone2;
    private String 1000;
    private String date1;
    private String 1010;
    private String date2;
    private String 1020;
    private String miscText1;
    private String 1030;
    private String miscText2;
    private String 1040;
    private String nbrOfCopies;
    private String 1050;
    private String endOfTrigger;
    private String 1060;
    private String testProdInd;
    private String 1070;
    private String anyCover;
    private String 1080;
    private String onlyCover;
    private String 1090;
    private String medCover;
    private String 1100;
    private String dentalCover;
    private String 1110;
    private String visionCover;
    private String 1120;
    private String prescCover;
    private String 1130;
    private String mentalCover;
    private String 1140;
    private String checkBox8;
    private String 1150;
    private String checkBox9;
    private String 1160;
    private String checkBox10;
    private String 1170;
    private String checkBox11;
    private String 1180;
    private String checkBox12;
    private String 1190;
    private String checkBox13;
    private String 1200;
    private String checkBox14;
    private String caseWorkerName;
    private String cwFirstName;
    private String cwMidName;
    private String cwMidInit;
    private String cwLastName;
    private String 0290;
    public String get1() {
        return 1;
    }

    public void set1(String 1 ) {
        this.1 = 1;
    }

    public String get0030() {
        return 0030;
    }

    public void set0030(String 0030 ) {
        this.0030 = 0030;
    }

    public String getToKeylineFmt() {
        return toKeylineFmt;
    }

    public void setToKeylineFmt(String toKeylineFmt ) {
        this.toKeylineFmt = toKeylineFmt;
    }

    public String get0040() {
        return 0040;
    }

    public void set0040(String 0040 ) {
        this.0040 = 0040;
    }

    public String getFormId() {
        return formId;
    }

    public void setFormId(String formId ) {
        this.formId = formId;
    }

    public String get0050() {
        return 0050;
    }

    public void set0050(String 0050 ) {
        this.0050 = 0050;
    }

    public String getPcktId() {
        return pcktId;
    }

    public void setPcktId(String pcktId ) {
        this.pcktId = pcktId;
    }

    public String get0060() {
        return 0060;
    }

    public void set0060(String 0060 ) {
        this.0060 = 0060;
    }

    public String getState() {
        return state;
    }

    public void setState(String state ) {
        this.state = state;
    }

    public String get0070() {
        return 0070;
    }

    public void set0070(String 0070 ) {
        this.0070 = 0070;
    }

    public String getCounty() {
        return county;
    }

    public void setCounty(String county ) {
        this.county = county;
    }

    public String get0080() {
        return 0080;
    }

    public void set0080(String 0080 ) {
        this.0080 = 0080;
    }

    public String getCivActNbr() {
        return civActNbr;
    }

    public void setCivActNbr(String civActNbr ) {
        this.civActNbr = civActNbr;
    }

    public String get0090() {
        return 0090;
    }

    public void set0090(String 0090 ) {
        this.0090 = 0090;
    }

    public String getEmpFein() {
        return empFein;
    }

    public void setEmpFein(String empFein ) {
        this.empFein = empFein;
    }

    public String get0100() {
        return 0100;
    }

    public void set0100(String 0100 ) {
        this.0100 = 0100;
    }

    public String getEmployer() {
        return employer;
    }

    public void setEmployer(String employer ) {
        this.employer = employer;
    }

    public String get0110() {
        return 0110;
    }

    public void set0110(String 0110 ) {
        this.0110 = 0110;
    }

    public String getEmpAdd1() {
        return empAdd1;
    }

    public void setEmpAdd1(String empAdd1 ) {
        this.empAdd1 = empAdd1;
    }

    public String get0120() {
        return 0120;
    }

    public void set0120(String 0120 ) {
        this.0120 = 0120;
    }

    public String getEmpAdd2() {
        return empAdd2;
    }

    public void setEmpAdd2(String empAdd2 ) {
        this.empAdd2 = empAdd2;
    }

    public String get0130() {
        return 0130;
    }

    public void set0130(String 0130 ) {
        this.0130 = 0130;
    }

    public String getEmpAdd3() {
        return empAdd3;
    }

    public void setEmpAdd3(String empAdd3 ) {
        this.empAdd3 = empAdd3;
    }

    public String get0140() {
        return 0140;
    }

    public void set0140(String 0140 ) {
        this.0140 = 0140;
    }

    public String getEmpCity() {
        return empCity;
    }

    public void setEmpCity(String empCity ) {
        this.empCity = empCity;
    }

    public String get0150() {
        return 0150;
    }

    public void set0150(String 0150 ) {
        this.0150 = 0150;
    }

    public String getEmpState() {
        return empState;
    }

    public void setEmpState(String empState ) {
        this.empState = empState;
    }

    public String get0160() {
        return 0160;
    }

    public void set0160(String 0160 ) {
        this.0160 = 0160;
    }

    public String getEmpZip() {
        return empZip;
    }

    public void setEmpZip(String empZip ) {
        this.empZip = empZip;
    }

    public String get0170() {
        return 0170;
    }

    public void set0170(String 0170 ) {
        this.0170 = 0170;
    }

    public String getEmpCountryName() {
        return empCountryName;
    }

    public void setEmpCountryName(String empCountryName ) {
        this.empCountryName = empCountryName;
    }

    public String get0180() {
        return 0180;
    }

    public void set0180(String 0180 ) {
        this.0180 = 0180;
    }

    public String getApLast() {
        return apLast;
    }

    public void setApLast(String apLast ) {
        this.apLast = apLast;
    }

    public String get0190() {
        return 0190;
    }

    public void set0190(String 0190 ) {
        this.0190 = 0190;
    }

    public String getApFirst() {
        return apFirst;
    }

    public void setApFirst(String apFirst ) {
        this.apFirst = apFirst;
    }

    public String get0200() {
        return 0200;
    }

    public void set0200(String 0200 ) {
        this.0200 = 0200;
    }

    public String getApMid() {
        return apMid;
    }

    public void setApMid(String apMid ) {
        this.apMid = apMid;
    }

    public String get0210() {
        return 0210;
    }

    public void set0210(String 0210 ) {
        this.0210 = 0210;
    }

    public String getApMod() {
        return apMod;
    }

    public void setApMod(String apMod ) {
        this.apMod = apMod;
    }

    public String get0220() {
        return 0220;
    }

    public void set0220(String 0220 ) {
        this.0220 = 0220;
    }

    public String getApSsn() {
        return apSsn;
    }

    public void setApSsn(String apSsn ) {
        this.apSsn = apSsn;
    }

    public String get0230() {
        return 0230;
    }

    public void set0230(String 0230 ) {
        this.0230 = 0230;
    }

    public String getCaseNbr1() {
        return caseNbr1;
    }

    public void setCaseNbr1(String caseNbr1 ) {
        this.caseNbr1 = caseNbr1;
    }

    public String get0240() {
        return 0240;
    }

    public void set0240(String 0240 ) {
        this.0240 = 0240;
    }

    public String getCtLast() {
        return ctLast;
    }

    public void setCtLast(String ctLast ) {
        this.ctLast = ctLast;
    }

    public String get0250() {
        return 0250;
    }

    public void set0250(String 0250 ) {
        this.0250 = 0250;
    }

    public String getCtFirst() {
        return ctFirst;
    }

    public void setCtFirst(String ctFirst ) {
        this.ctFirst = ctFirst;
    }

    public String get0260() {
        return 0260;
    }

    public void set0260(String 0260 ) {
        this.0260 = 0260;
    }

    public String getCtMid() {
        return ctMid;
    }

    public void setCtMid(String ctMid ) {
        this.ctMid = ctMid;
    }

    public String get0270() {
        return 0270;
    }

    public void set0270(String 0270 ) {
        this.0270 = 0270;
    }

    public String getCtMod() {
        return ctMod;
    }

    public void setCtMod(String ctMod ) {
        this.ctMod = ctMod;
    }

    public String get0280() {
        return 0280;
    }

    public void set0280(String 0280 ) {
        this.0280 = 0280;
    }

    public String getOblgAmt() {
        return oblgAmt;
    }

    public void setOblgAmt(String oblgAmt ) {
        this.oblgAmt = oblgAmt;
    }

    public String get20290() {
        return 20290;
    }

    public void set20290(String 20290 ) {
        this.20290 = 20290;
    }

    public String getCsFreq() {
        return csFreq;
    }

    public void setCsFreq(String csFreq ) {
        this.csFreq = csFreq;
    }

    public String get0300() {
        return 0300;
    }

    public void set0300(String 0300 ) {
        this.0300 = 0300;
    }

    public String getArrears() {
        return arrears;
    }

    public void setArrears(String arrears ) {
        this.arrears = arrears;
    }

    public String get20310() {
        return 20310;
    }

    public void set20310(String 20310 ) {
        this.20310 = 20310;
    }

    public String getPastCsFreq() {
        return pastCsFreq;
    }

    public void setPastCsFreq(String pastCsFreq ) {
        this.pastCsFreq = pastCsFreq;
    }

    public String get0320() {
        return 0320;
    }

    public void set0320(String 0320 ) {
        this.0320 = 0320;
    }

    public String getArrears12wks() {
        return arrears12wks;
    }

    public void setArrears12wks(String arrears12wks ) {
        this.arrears12wks = arrears12wks;
    }

    public String get0330() {
        return 0330;
    }

    public void set0330(String 0330 ) {
        this.0330 = 0330;
    }

    public String getMedical() {
        return medical;
    }

    public void setMedical(String medical ) {
        this.medical = medical;
    }

    public String get20340() {
        return 20340;
    }

    public void set20340(String 20340 ) {
        this.20340 = 20340;
    }

    public String getMedFreq() {
        return medFreq;
    }

    public void setMedFreq(String medFreq ) {
        this.medFreq = medFreq;
    }

    public String get0350() {
        return 0350;
    }

    public void set0350(String 0350 ) {
        this.0350 = 0350;
    }

    public String getPastMedical() {
        return pastMedical;
    }

    public void setPastMedical(String pastMedical ) {
        this.pastMedical = pastMedical;
    }

    public String get20360() {
        return 20360;
    }

    public void set20360(String 20360 ) {
        this.20360 = 20360;
    }

    public String getPastMedFreq() {
        return pastMedFreq;
    }

    public void setPastMedFreq(String pastMedFreq ) {
        this.pastMedFreq = pastMedFreq;
    }

    public String get0370() {
        return 0370;
    }

    public void set0370(String 0370 ) {
        this.0370 = 0370;
    }

    public String getSpousal() {
        return spousal;
    }

    public void setSpousal(String spousal ) {
        this.spousal = spousal;
    }

    public String get20380() {
        return 20380;
    }

    public void set20380(String 20380 ) {
        this.20380 = 20380;
    }

    public String getSpousalFreq() {
        return spousalFreq;
    }

    public void setSpousalFreq(String spousalFreq ) {
        this.spousalFreq = spousalFreq;
    }

    public String get0390() {
        return 0390;
    }

    public void set0390(String 0390 ) {
        this.0390 = 0390;
    }

    public String getPastSpousal() {
        return pastSpousal;
    }

    public void setPastSpousal(String pastSpousal ) {
        this.pastSpousal = pastSpousal;
    }

    public String get20400() {
        return 20400;
    }

    public void set20400(String 20400 ) {
        this.20400 = 20400;
    }

    public String getPastSpousalFreq() {
        return pastSpousalFreq;
    }

    public void setPastSpousalFreq(String pastSpousalFreq ) {
        this.pastSpousalFreq = pastSpousalFreq;
    }

    public String get0410() {
        return 0410;
    }

    public void set0410(String 0410 ) {
        this.0410 = 0410;
    }

    public String getTotalAmt() {
        return totalAmt;
    }

    public void setTotalAmt(String totalAmt ) {
        this.totalAmt = totalAmt;
    }

    public String get20420() {
        return 20420;
    }

    public void set20420(String 20420 ) {
        this.20420 = 20420;
    }

    public String getWeeklyPay() {
        return weeklyPay;
    }

    public void setWeeklyPay(String weeklyPay ) {
        this.weeklyPay = weeklyPay;
    }

    public String get20430() {
        return 20430;
    }

    public void set20430(String 20430 ) {
        this.20430 = 20430;
    }

    public String getBiweeklyPay() {
        return biweeklyPay;
    }

    public void setBiweeklyPay(String biweeklyPay ) {
        this.biweeklyPay = biweeklyPay;
    }

    public String get20440() {
        return 20440;
    }

    public void set20440(String 20440 ) {
        this.20440 = 20440;
    }

    public String getSemimnthPay() {
        return semimnthPay;
    }

    public void setSemimnthPay(String semimnthPay ) {
        this.semimnthPay = semimnthPay;
    }

    public String get20450() {
        return 20450;
    }

    public void set20450(String 20450 ) {
        this.20450 = 20450;
    }

    public String getAgencyPayee() {
        return agencyPayee;
    }

    public void setAgencyPayee(String agencyPayee ) {
        this.agencyPayee = agencyPayee;
    }

    public String get0460() {
        return 0460;
    }

    public void set0460(String 0460 ) {
        this.0460 = 0460;
    }

    public String getPayeeAdd1() {
        return payeeAdd1;
    }

    public void setPayeeAdd1(String payeeAdd1 ) {
        this.payeeAdd1 = payeeAdd1;
    }

    public String get0470() {
        return 0470;
    }

    public void set0470(String 0470 ) {
        this.0470 = 0470;
    }

    public String getPayeeAdd2() {
        return payeeAdd2;
    }

    public void setPayeeAdd2(String payeeAdd2 ) {
        this.payeeAdd2 = payeeAdd2;
    }

    public String get0480() {
        return 0480;
    }

    public void set0480(String 0480 ) {
        this.0480 = 0480;
    }

    public String getPayeeCity() {
        return payeeCity;
    }

    public void setPayeeCity(String payeeCity ) {
        this.payeeCity = payeeCity;
    }

    public String get0490() {
        return 0490;
    }

    public void set0490(String 0490 ) {
        this.0490 = 0490;
    }

    public String getPayeeState() {
        return payeeState;
    }

    public void setPayeeState(String payeeState ) {
        this.payeeState = payeeState;
    }

    public String get0500() {
        return 0500;
    }

    public void set0500(String 0500 ) {
        this.0500 = 0500;
    }

    public String getPayeeZip() {
        return payeeZip;
    }

    public void setPayeeZip(String payeeZip ) {
        this.payeeZip = payeeZip;
    }

    public String get0510() {
        return 0510;
    }

    public void set0510(String 0510 ) {
        this.0510 = 0510;
    }

    public String getPayeeFipsCode() {
        return payeeFipsCode;
    }

    public void setPayeeFipsCode(String payeeFipsCode ) {
        this.payeeFipsCode = payeeFipsCode;
    }

    public String get0520() {
        return 0520;
    }

    public void set0520(String 0520 ) {
        this.0520 = 0520;
    }

    public String getWorkerName() {
        return workerName;
    }

    public void setWorkerName(String workerName ) {
        this.workerName = workerName;
    }

    public String get0530() {
        return 0530;
    }

    public void set0530(String 0530 ) {
        this.0530 = 0530;
    }

    public String getDocDate() {
        return docDate;
    }

    public void setDocDate(String docDate ) {
        this.docDate = docDate;
    }

    public String get0540() {
        return 0540;
    }

    public void set0540(String 0540 ) {
        this.0540 = 0540;
    }

    public String getOtherDue() {
        return otherDue;
    }

    public void setOtherDue(String otherDue ) {
        this.otherDue = otherDue;
    }

    public String get20550() {
        return 20550;
    }

    public void set20550(String 20550 ) {
        this.20550 = 20550;
    }

    public String getOtherDueFreq() {
        return otherDueFreq;
    }

    public void setOtherDueFreq(String otherDueFreq ) {
        this.otherDueFreq = otherDueFreq;
    }

    public String get0560() {
        return 0560;
    }

    public void set0560(String 0560 ) {
        this.0560 = 0560;
    }

    public String getOtherDueDesc() {
        return otherDueDesc;
    }

    public void setOtherDueDesc(String otherDueDesc ) {
        this.otherDueDesc = otherDueDesc;
    }

    public String get0570() {
        return 0570;
    }

    public void set0570(String 0570 ) {
        this.0570 = 0570;
    }

    public String getAddInfo1() {
        return addInfo1;
    }

    public void setAddInfo1(String addInfo1 ) {
        this.addInfo1 = addInfo1;
    }

    public String get0580() {
        return 0580;
    }

    public void set0580(String 0580 ) {
        this.0580 = 0580;
    }

    public String getAddInfo2() {
        return addInfo2;
    }

    public void setAddInfo2(String addInfo2 ) {
        this.addInfo2 = addInfo2;
    }

    public String get0590() {
        return 0590;
    }

    public void set0590(String 0590 ) {
        this.0590 = 0590;
    }

    public String getAddInfo3() {
        return addInfo3;
    }

    public void setAddInfo3(String addInfo3 ) {
        this.addInfo3 = addInfo3;
    }

    public String get0600() {
        return 0600;
    }

    public void set0600(String 0600 ) {
        this.0600 = 0600;
    }

    public String getChildArray() {
        return childArray;
    }

    public void setChildArray(String childArray ) {
        this.childArray = childArray;
    }

    public String get0620() {
        return 0620;
    }

    public void set0620(String 0620 ) {
        this.0620 = 0620;
    }

    public String getPhoneExtn() {
        return phoneExtn;
    }

    public void setPhoneExtn(String phoneExtn ) {
        this.phoneExtn = phoneExtn;
    }

    public String get0630() {
        return 0630;
    }

    public void set0630(String 0630 ) {
        this.0630 = 0630;
    }

    public String getFaxNbr() {
        return faxNbr;
    }

    public void setFaxNbr(String faxNbr ) {
        this.faxNbr = faxNbr;
    }

    public String get0640() {
        return 0640;
    }

    public void set0640(String 0640 ) {
        this.0640 = 0640;
    }

    public String getWorkerEmail() {
        return workerEmail;
    }

    public void setWorkerEmail(String workerEmail ) {
        this.workerEmail = workerEmail;
    }

    public String get0650() {
        return 0650;
    }

    public void set0650(String 0650 ) {
        this.0650 = 0650;
    }

    public String getFormPrinted() {
        return formPrinted;
    }

    public void setFormPrinted(String formPrinted ) {
        this.formPrinted = formPrinted;
    }

    public String get0660() {
        return 0660;
    }

    public void set0660(String 0660 ) {
        this.0660 = 0660;
    }

    public String getFormType() {
        return formType;
    }

    public void setFormType(String formType ) {
        this.formType = formType;
    }

    public String get0670() {
        return 0670;
    }

    public void set0670(String 0670 ) {
        this.0670 = 0670;
    }

    public String getWrkrUid() {
        return wrkrUid;
    }

    public void setWrkrUid(String wrkrUid ) {
        this.wrkrUid = wrkrUid;
    }

    public String get0680() {
        return 0680;
    }

    public void set0680(String 0680 ) {
        this.0680 = 0680;
    }

    public String getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(String timeStamp ) {
        this.timeStamp = timeStamp;
    }

    public String get0690() {
        return 0690;
    }

    public void set0690(String 0690 ) {
        this.0690 = 0690;
    }

    public String getCaseId() {
        return caseId;
    }

    public void setCaseId(String caseId ) {
        this.caseId = caseId;
    }

    public String get0700() {
        return 0700;
    }

    public void set0700(String 0700 ) {
        this.0700 = 0700;
    }

    public String getApAdd1() {
        return apAdd1;
    }

    public void setApAdd1(String apAdd1 ) {
        this.apAdd1 = apAdd1;
    }

    public String get0710() {
        return 0710;
    }

    public void set0710(String 0710 ) {
        this.0710 = 0710;
    }

    public String getApAdd2() {
        return apAdd2;
    }

    public void setApAdd2(String apAdd2 ) {
        this.apAdd2 = apAdd2;
    }

    public String get0720() {
        return 0720;
    }

    public void set0720(String 0720 ) {
        this.0720 = 0720;
    }

    public String getApAdd3() {
        return apAdd3;
    }

    public void setApAdd3(String apAdd3 ) {
        this.apAdd3 = apAdd3;
    }

    public String get0730() {
        return 0730;
    }

    public void set0730(String 0730 ) {
        this.0730 = 0730;
    }

    public String getApCity() {
        return apCity;
    }

    public void setApCity(String apCity ) {
        this.apCity = apCity;
    }

    public String get0740() {
        return 0740;
    }

    public void set0740(String 0740 ) {
        this.0740 = 0740;
    }

    public String getApState() {
        return apState;
    }

    public void setApState(String apState ) {
        this.apState = apState;
    }

    public String get0750() {
        return 0750;
    }

    public void set0750(String 0750 ) {
        this.0750 = 0750;
    }

    public String getApZip() {
        return apZip;
    }

    public void setApZip(String apZip ) {
        this.apZip = apZip;
    }

    public String get0760() {
        return 0760;
    }

    public void set0760(String 0760 ) {
        this.0760 = 0760;
    }

    public String getApCountry() {
        return apCountry;
    }

    public void setApCountry(String apCountry ) {
        this.apCountry = apCountry;
    }

    public String get0770() {
        return 0770;
    }

    public void set0770(String 0770 ) {
        this.0770 = 0770;
    }

    public String getCtAdd1() {
        return ctAdd1;
    }

    public void setCtAdd1(String ctAdd1 ) {
        this.ctAdd1 = ctAdd1;
    }

    public String get0780() {
        return 0780;
    }

    public void set0780(String 0780 ) {
        this.0780 = 0780;
    }

    public String getCtAdd2() {
        return ctAdd2;
    }

    public void setCtAdd2(String ctAdd2 ) {
        this.ctAdd2 = ctAdd2;
    }

    public String get0790() {
        return 0790;
    }

    public void set0790(String 0790 ) {
        this.0790 = 0790;
    }

    public String getCtAdd3() {
        return ctAdd3;
    }

    public void setCtAdd3(String ctAdd3 ) {
        this.ctAdd3 = ctAdd3;
    }

    public String get0800() {
        return 0800;
    }

    public void set0800(String 0800 ) {
        this.0800 = 0800;
    }

    public String getCtCity() {
        return ctCity;
    }

    public void setCtCity(String ctCity ) {
        this.ctCity = ctCity;
    }

    public String get0810() {
        return 0810;
    }

    public void set0810(String 0810 ) {
        this.0810 = 0810;
    }

    public String getCtState() {
        return ctState;
    }

    public void setCtState(String ctState ) {
        this.ctState = ctState;
    }

    public String get0820() {
        return 0820;
    }

    public void set0820(String 0820 ) {
        this.0820 = 0820;
    }

    public String getCtZip() {
        return ctZip;
    }

    public void setCtZip(String ctZip ) {
        this.ctZip = ctZip;
    }

    public String get0830() {
        return 0830;
    }

    public void set0830(String 0830 ) {
        this.0830 = 0830;
    }

    public String getCtCountry() {
        return ctCountry;
    }

    public void setCtCountry(String ctCountry ) {
        this.ctCountry = ctCountry;
    }

    public String get0840() {
        return 0840;
    }

    public void set0840(String 0840 ) {
        this.0840 = 0840;
    }

    public String getWrkrAdd1() {
        return wrkrAdd1;
    }

    public void setWrkrAdd1(String wrkrAdd1 ) {
        this.wrkrAdd1 = wrkrAdd1;
    }

    public String get0850() {
        return 0850;
    }

    public void set0850(String 0850 ) {
        this.0850 = 0850;
    }

    public String getWrkrAdd2() {
        return wrkrAdd2;
    }

    public void setWrkrAdd2(String wrkrAdd2 ) {
        this.wrkrAdd2 = wrkrAdd2;
    }

    public String get0860() {
        return 0860;
    }

    public void set0860(String 0860 ) {
        this.0860 = 0860;
    }

    public String getWrkrCity() {
        return wrkrCity;
    }

    public void setWrkrCity(String wrkrCity ) {
        this.wrkrCity = wrkrCity;
    }

    public String get0870() {
        return 0870;
    }

    public void set0870(String 0870 ) {
        this.0870 = 0870;
    }

    public String getWrkrState() {
        return wrkrState;
    }

    public void setWrkrState(String wrkrState ) {
        this.wrkrState = wrkrState;
    }

    public String get0880() {
        return 0880;
    }

    public void set0880(String 0880 ) {
        this.0880 = 0880;
    }

    public String getWrkrZip() {
        return wrkrZip;
    }

    public void setWrkrZip(String wrkrZip ) {
        this.wrkrZip = wrkrZip;
    }

    public String get0890() {
        return 0890;
    }

    public void set0890(String 0890 ) {
        this.0890 = 0890;
    }

    public String getUidCreated() {
        return uidCreated;
    }

    public void setUidCreated(String uidCreated ) {
        this.uidCreated = uidCreated;
    }

    public String get0900() {
        return 0900;
    }

    public void set0900(String 0900 ) {
        this.0900 = 0900;
    }

    public String getOblgState() {
        return oblgState;
    }

    public void setOblgState(String oblgState ) {
        this.oblgState = oblgState;
    }

    public String get0910() {
        return 0910;
    }

    public void set0910(String 0910 ) {
        this.0910 = 0910;
    }

    public String getBankRouting() {
        return bankRouting;
    }

    public void setBankRouting(String bankRouting ) {
        this.bankRouting = bankRouting;
    }

    public String get0920() {
        return 0920;
    }

    public void set0920(String 0920 ) {
        this.0920 = 0920;
    }

    public String getBankAccount() {
        return bankAccount;
    }

    public void setBankAccount(String bankAccount ) {
        this.bankAccount = bankAccount;
    }

    public String get0930() {
        return 0930;
    }

    public void set0930(String 0930 ) {
        this.0930 = 0930;
    }

    public String getEnvInd() {
        return envInd;
    }

    public void setEnvInd(String envInd ) {
        this.envInd = envInd;
    }

    public String get0940() {
        return 0940;
    }

    public void set0940(String 0940 ) {
        this.0940 = 0940;
    }

    public String getEmprUnit() {
        return emprUnit;
    }

    public void setEmprUnit(String emprUnit ) {
        this.emprUnit = emprUnit;
    }

    public String get0950() {
        return 0950;
    }

    public void set0950(String 0950 ) {
        this.0950 = 0950;
    }

    public String getEmprPhone() {
        return emprPhone;
    }

    public void setEmprPhone(String emprPhone ) {
        this.emprPhone = emprPhone;
    }

    public String get0960() {
        return 0960;
    }

    public void set0960(String 0960 ) {
        this.0960 = 0960;
    }

    public String getEmprFax() {
        return emprFax;
    }

    public void setEmprFax(String emprFax ) {
        this.emprFax = emprFax;
    }

    public String get0970() {
        return 0970;
    }

    public void set0970(String 0970 ) {
        this.0970 = 0970;
    }

    public String getLumpSumAmt() {
        return lumpSumAmt;
    }

    public void setLumpSumAmt(String lumpSumAmt ) {
        this.lumpSumAmt = lumpSumAmt;
    }

    public String get20980() {
        return 20980;
    }

    public void set20980(String 20980 ) {
        this.20980 = 20980;
    }

    public String getTelephone1() {
        return telephone1;
    }

    public void setTelephone1(String telephone1 ) {
        this.telephone1 = telephone1;
    }

    public String get0990() {
        return 0990;
    }

    public void set0990(String 0990 ) {
        this.0990 = 0990;
    }

    public String getTelephone2() {
        return telephone2;
    }

    public void setTelephone2(String telephone2 ) {
        this.telephone2 = telephone2;
    }

    public String get1000() {
        return 1000;
    }

    public void set1000(String 1000 ) {
        this.1000 = 1000;
    }

    public String getDate1() {
        return date1;
    }

    public void setDate1(String date1 ) {
        this.date1 = date1;
    }

    public String get1010() {
        return 1010;
    }

    public void set1010(String 1010 ) {
        this.1010 = 1010;
    }

    public String getDate2() {
        return date2;
    }

    public void setDate2(String date2 ) {
        this.date2 = date2;
    }

    public String get1020() {
        return 1020;
    }

    public void set1020(String 1020 ) {
        this.1020 = 1020;
    }

    public String getMiscText1() {
        return miscText1;
    }

    public void setMiscText1(String miscText1 ) {
        this.miscText1 = miscText1;
    }

    public String get1030() {
        return 1030;
    }

    public void set1030(String 1030 ) {
        this.1030 = 1030;
    }

    public String getMiscText2() {
        return miscText2;
    }

    public void setMiscText2(String miscText2 ) {
        this.miscText2 = miscText2;
    }

    public String get1040() {
        return 1040;
    }

    public void set1040(String 1040 ) {
        this.1040 = 1040;
    }

    public String getNbrOfCopies() {
        return nbrOfCopies;
    }

    public void setNbrOfCopies(String nbrOfCopies ) {
        this.nbrOfCopies = nbrOfCopies;
    }

    public String get1050() {
        return 1050;
    }

    public void set1050(String 1050 ) {
        this.1050 = 1050;
    }

    public String getEndOfTrigger() {
        return endOfTrigger;
    }

    public void setEndOfTrigger(String endOfTrigger ) {
        this.endOfTrigger = endOfTrigger;
    }

    public String get1060() {
        return 1060;
    }

    public void set1060(String 1060 ) {
        this.1060 = 1060;
    }

    public String getTestProdInd() {
        return testProdInd;
    }

    public void setTestProdInd(String testProdInd ) {
        this.testProdInd = testProdInd;
    }

    public String get1070() {
        return 1070;
    }

    public void set1070(String 1070 ) {
        this.1070 = 1070;
    }

    public String getAnyCover() {
        return anyCover;
    }

    public void setAnyCover(String anyCover ) {
        this.anyCover = anyCover;
    }

    public String get1080() {
        return 1080;
    }

    public void set1080(String 1080 ) {
        this.1080 = 1080;
    }

    public String getOnlyCover() {
        return onlyCover;
    }

    public void setOnlyCover(String onlyCover ) {
        this.onlyCover = onlyCover;
    }

    public String get1090() {
        return 1090;
    }

    public void set1090(String 1090 ) {
        this.1090 = 1090;
    }

    public String getMedCover() {
        return medCover;
    }

    public void setMedCover(String medCover ) {
        this.medCover = medCover;
    }

    public String get1100() {
        return 1100;
    }

    public void set1100(String 1100 ) {
        this.1100 = 1100;
    }

    public String getDentalCover() {
        return dentalCover;
    }

    public void setDentalCover(String dentalCover ) {
        this.dentalCover = dentalCover;
    }

    public String get1110() {
        return 1110;
    }

    public void set1110(String 1110 ) {
        this.1110 = 1110;
    }

    public String getVisionCover() {
        return visionCover;
    }

    public void setVisionCover(String visionCover ) {
        this.visionCover = visionCover;
    }

    public String get1120() {
        return 1120;
    }

    public void set1120(String 1120 ) {
        this.1120 = 1120;
    }

    public String getPrescCover() {
        return prescCover;
    }

    public void setPrescCover(String prescCover ) {
        this.prescCover = prescCover;
    }

    public String get1130() {
        return 1130;
    }

    public void set1130(String 1130 ) {
        this.1130 = 1130;
    }

    public String getMentalCover() {
        return mentalCover;
    }

    public void setMentalCover(String mentalCover ) {
        this.mentalCover = mentalCover;
    }

    public String get1140() {
        return 1140;
    }

    public void set1140(String 1140 ) {
        this.1140 = 1140;
    }

    public String getCheckBox8() {
        return checkBox8;
    }

    public void setCheckBox8(String checkBox8 ) {
        this.checkBox8 = checkBox8;
    }

    public String get1150() {
        return 1150;
    }

    public void set1150(String 1150 ) {
        this.1150 = 1150;
    }

    public String getCheckBox9() {
        return checkBox9;
    }

    public void setCheckBox9(String checkBox9 ) {
        this.checkBox9 = checkBox9;
    }

    public String get1160() {
        return 1160;
    }

    public void set1160(String 1160 ) {
        this.1160 = 1160;
    }

    public String getCheckBox10() {
        return checkBox10;
    }

    public void setCheckBox10(String checkBox10 ) {
        this.checkBox10 = checkBox10;
    }

    public String get1170() {
        return 1170;
    }

    public void set1170(String 1170 ) {
        this.1170 = 1170;
    }

    public String getCheckBox11() {
        return checkBox11;
    }

    public void setCheckBox11(String checkBox11 ) {
        this.checkBox11 = checkBox11;
    }

    public String get1180() {
        return 1180;
    }

    public void set1180(String 1180 ) {
        this.1180 = 1180;
    }

    public String getCheckBox12() {
        return checkBox12;
    }

    public void setCheckBox12(String checkBox12 ) {
        this.checkBox12 = checkBox12;
    }

    public String get1190() {
        return 1190;
    }

    public void set1190(String 1190 ) {
        this.1190 = 1190;
    }

    public String getCheckBox13() {
        return checkBox13;
    }

    public void setCheckBox13(String checkBox13 ) {
        this.checkBox13 = checkBox13;
    }

    public String get1200() {
        return 1200;
    }

    public void set1200(String 1200 ) {
        this.1200 = 1200;
    }

    public String getCheckBox14() {
        return checkBox14;
    }

    public void setCheckBox14(String checkBox14 ) {
        this.checkBox14 = checkBox14;
    }

    public String getCaseWorkerName() {
        return caseWorkerName;
    }

    public void setCaseWorkerName(String caseWorkerName ) {
        this.caseWorkerName = caseWorkerName;
    }

    public String getCwFirstName() {
        return cwFirstName;
    }

    public void setCwFirstName(String cwFirstName ) {
        this.cwFirstName = cwFirstName;
    }

    public String getCwMidName() {
        return cwMidName;
    }

    public void setCwMidName(String cwMidName ) {
        this.cwMidName = cwMidName;
    }

    public String getCwMidInit() {
        return cwMidInit;
    }

    public void setCwMidInit(String cwMidInit ) {
        this.cwMidInit = cwMidInit;
    }

    public String getCwLastName() {
        return cwLastName;
    }

    public void setCwLastName(String cwLastName ) {
        this.cwLastName = cwLastName;
    }

    public String get0290() {
        return 0290;
    }

    public void set0290(String 0290 ) {
        this.0290 = 0290;
    }

    @Override
    public String toString() {
        return "Weo5sdly [1 =" + 1 + " ,0030 =" + 0030 + " ,toKeylineFmt =" + toKeylineFmt + " ,0040 =" + 0040 + " ,formId =" + formId + " ,0050 =" + 0050 + " ,pcktId =" + pcktId + " ,0060 =" + 0060 + " ,state =" + state + " ,0070 =" + 0070 + " ,county =" + county + " ,0080 =" + 0080 + " ,civActNbr =" + civActNbr + " ,0090 =" + 0090 + " ,empFein =" + empFein + " ,0100 =" + 0100 + " ,employer =" + employer + " ,0110 =" + 0110 + " ,empAdd1 =" + empAdd1 + " ,0120 =" + 0120 + " ,empAdd2 =" + empAdd2 + " ,0130 =" + 0130 + " ,empAdd3 =" + empAdd3 + " ,0140 =" + 0140 + " ,empCity =" + empCity + " ,0150 =" + 0150 + " ,empState =" + empState + " ,0160 =" + 0160 + " ,empZip =" + empZip + " ,0170 =" + 0170 + " ,empCountryName =" + empCountryName + " ,0180 =" + 0180 + " ,apLast =" + apLast + " ,0190 =" + 0190 + " ,apFirst =" + apFirst + " ,0200 =" + 0200 + " ,apMid =" + apMid + " ,0210 =" + 0210 + " ,apMod =" + apMod + " ,0220 =" + 0220 + " ,apSsn =" + apSsn + " ,0230 =" + 0230 + " ,caseNbr1 =" + caseNbr1 + " ,0240 =" + 0240 + " ,ctLast =" + ctLast + " ,0250 =" + 0250 + " ,ctFirst =" + ctFirst + " ,0260 =" + 0260 + " ,ctMid =" + ctMid + " ,0270 =" + 0270 + " ,ctMod =" + ctMod + " ,0280 =" + 0280 + " ,oblgAmt =" + oblgAmt + " ,20290 =" + 20290 + " ,csFreq =" + csFreq + " ,0300 =" + 0300 + " ,arrears =" + arrears + " ,20310 =" + 20310 + " ,pastCsFreq =" + pastCsFreq + " ,0320 =" + 0320 + " ,arrears12wks =" + arrears12wks + " ,0330 =" + 0330 + " ,medical =" + medical + " ,20340 =" + 20340 + " ,medFreq =" + medFreq + " ,0350 =" + 0350 + " ,pastMedical =" + pastMedical + " ,20360 =" + 20360 + " ,pastMedFreq =" + pastMedFreq + " ,0370 =" + 0370 + " ,spousal =" + spousal + " ,20380 =" + 20380 + " ,spousalFreq =" + spousalFreq + " ,0390 =" + 0390 + " ,pastSpousal =" + pastSpousal + " ,20400 =" + 20400 + " ,pastSpousalFreq =" + pastSpousalFreq + " ,0410 =" + 0410 + " ,totalAmt =" + totalAmt + " ,20420 =" + 20420 + " ,weeklyPay =" + weeklyPay + " ,20430 =" + 20430 + " ,biweeklyPay =" + biweeklyPay + " ,20440 =" + 20440 + " ,semimnthPay =" + semimnthPay + " ,20450 =" + 20450 + " ,agencyPayee =" + agencyPayee + " ,0460 =" + 0460 + " ,payeeAdd1 =" + payeeAdd1 + " ,0470 =" + 0470 + " ,payeeAdd2 =" + payeeAdd2 + " ,0480 =" + 0480 + " ,payeeCity =" + payeeCity + " ,0490 =" + 0490 + " ,payeeState =" + payeeState + " ,0500 =" + 0500 + " ,payeeZip =" + payeeZip + " ,0510 =" + 0510 + " ,payeeFipsCode =" + payeeFipsCode + " ,0520 =" + 0520 + " ,workerName =" + workerName + " ,0530 =" + 0530 + " ,docDate =" + docDate + " ,0540 =" + 0540 + " ,otherDue =" + otherDue + " ,20550 =" + 20550 + " ,otherDueFreq =" + otherDueFreq + " ,0560 =" + 0560 + " ,otherDueDesc =" + otherDueDesc + " ,0570 =" + 0570 + " ,addInfo1 =" + addInfo1 + " ,0580 =" + 0580 + " ,addInfo2 =" + addInfo2 + " ,0590 =" + 0590 + " ,addInfo3 =" + addInfo3 + " ,0600 =" + 0600 + " ,childArray =" + childArray + " ,0620 =" + 0620 + " ,phoneExtn =" + phoneExtn + " ,0630 =" + 0630 + " ,faxNbr =" + faxNbr + " ,0640 =" + 0640 + " ,workerEmail =" + workerEmail + " ,0650 =" + 0650 + " ,formPrinted =" + formPrinted + " ,0660 =" + 0660 + " ,formType =" + formType + " ,0670 =" + 0670 + " ,wrkrUid =" + wrkrUid + " ,0680 =" + 0680 + " ,timeStamp =" + timeStamp + " ,0690 =" + 0690 + " ,caseId =" + caseId + " ,0700 =" + 0700 + " ,apAdd1 =" + apAdd1 + " ,0710 =" + 0710 + " ,apAdd2 =" + apAdd2 + " ,0720 =" + 0720 + " ,apAdd3 =" + apAdd3 + " ,0730 =" + 0730 + " ,apCity =" + apCity + " ,0740 =" + 0740 + " ,apState =" + apState + " ,0750 =" + 0750 + " ,apZip =" + apZip + " ,0760 =" + 0760 + " ,apCountry =" + apCountry + " ,0770 =" + 0770 + " ,ctAdd1 =" + ctAdd1 + " ,0780 =" + 0780 + " ,ctAdd2 =" + ctAdd2 + " ,0790 =" + 0790 + " ,ctAdd3 =" + ctAdd3 + " ,0800 =" + 0800 + " ,ctCity =" + ctCity + " ,0810 =" + 0810 + " ,ctState =" + ctState + " ,0820 =" + 0820 + " ,ctZip =" + ctZip + " ,0830 =" + 0830 + " ,ctCountry =" + ctCountry + " ,0840 =" + 0840 + " ,wrkrAdd1 =" + wrkrAdd1 + " ,0850 =" + 0850 + " ,wrkrAdd2 =" + wrkrAdd2 + " ,0860 =" + 0860 + " ,wrkrCity =" + wrkrCity + " ,0870 =" + 0870 + " ,wrkrState =" + wrkrState + " ,0880 =" + 0880 + " ,wrkrZip =" + wrkrZip + " ,0890 =" + 0890 + " ,uidCreated =" + uidCreated + " ,0900 =" + 0900 + " ,oblgState =" + oblgState + " ,0910 =" + 0910 + " ,bankRouting =" + bankRouting + " ,0920 =" + 0920 + " ,bankAccount =" + bankAccount + " ,0930 =" + 0930 + " ,envInd =" + envInd + " ,0940 =" + 0940 + " ,emprUnit =" + emprUnit + " ,0950 =" + 0950 + " ,emprPhone =" + emprPhone + " ,0960 =" + 0960 + " ,emprFax =" + emprFax + " ,0970 =" + 0970 + " ,lumpSumAmt =" + lumpSumAmt + " ,20980 =" + 20980 + " ,telephone1 =" + telephone1 + " ,0990 =" + 0990 + " ,telephone2 =" + telephone2 + " ,1000 =" + 1000 + " ,date1 =" + date1 + " ,1010 =" + 1010 + " ,date2 =" + date2 + " ,1020 =" + 1020 + " ,miscText1 =" + miscText1 + " ,1030 =" + 1030 + " ,miscText2 =" + miscText2 + " ,1040 =" + 1040 + " ,nbrOfCopies =" + nbrOfCopies + " ,1050 =" + 1050 + " ,endOfTrigger =" + endOfTrigger + " ,1060 =" + 1060 + " ,testProdInd =" + testProdInd + " ,1070 =" + 1070 + " ,anyCover =" + anyCover + " ,1080 =" + 1080 + " ,onlyCover =" + onlyCover + " ,1090 =" + 1090 + " ,medCover =" + medCover + " ,1100 =" + 1100 + " ,dentalCover =" + dentalCover + " ,1110 =" + 1110 + " ,visionCover =" + visionCover + " ,1120 =" + 1120 + " ,prescCover =" + prescCover + " ,1130 =" + 1130 + " ,mentalCover =" + mentalCover + " ,1140 =" + 1140 + " ,checkBox8 =" + checkBox8 + " ,1150 =" + 1150 + " ,checkBox9 =" + checkBox9 + " ,1160 =" + 1160 + " ,checkBox10 =" + checkBox10 + " ,1170 =" + 1170 + " ,checkBox11 =" + checkBox11 + " ,1180 =" + 1180 + " ,checkBox12 =" + checkBox12 + " ,1190 =" + 1190 + " ,checkBox13 =" + checkBox13 + " ,1200 =" + 1200 + " ,checkBox14 =" + checkBox14 + " ,caseWorkerName =" + caseWorkerName + " ,cwFirstName =" + cwFirstName + " ,cwMidName =" + cwMidName + " ,cwMidInit =" + cwMidInit + " ,cwLastName =" + cwLastName + " ,0290 =" + 0290+ "]";
    }
}