package com.oscar.swv.dataobject;

import java.io.Serializable;
import java.util.List;

import com.swv.oscar.dataobject.common.BaseBO;

import java.util.ArrayList;

/*************************************************************************
 *
 * OSCAR CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * OSCAR is a trademark of OSCAR Company.
 *
 * Copyright © 2017 OSCAR. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of OSCAR
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to OSCAR and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from OSCAR.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo5sdlyBO extends BaseBO implements Serializable {


    private List<Weo5sdly> weo5sdly;
    private int exeStatus;
    public List<Weo5sdly> getWeo5sdly() {
        if(weo5sdly == null) {
            weo5sdly = new ArrayList<Weo5sdly>();
        }
        return weo5sdly;
    }

    public void setWeo5sdly(List<Weo5sdly> weo5sdly ) {
        this.weo5sdly = weo5sdly;
    }

    public int getExeStatus() {
        return exeStatus;
    }

    public void setExeStatus(int exeStatus ) {
        this.exeStatus = exeStatus;
    }

    @Override
    public String toString() {
        return "Weo5sdlyBO [weo5sdly =" + weo5sdly + " ,exeStatus =" + exeStatus+ "]";
    }
}