package com.oscar.swv.dataobject;

import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;

/*************************************************************************
 *
 * OSCAR CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * OSCAR is a trademark of OSCAR Company.
 *
 * Copyright © 2017 OSCAR. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of OSCAR
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to OSCAR and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from OSCAR.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo5sfv1   implements Serializable {

    private int personPin;
    private int fvRc;
    private int fvCaseId;
    public int getPersonPin() {
        return personPin;
    }

    public void setPersonPin(int personPin ) {
        this.personPin = personPin;
    }

    public int getFvRc() {
        return fvRc;
    }

    public void setFvRc(int fvRc ) {
        this.fvRc = fvRc;
    }

    public int getFvCaseId() {
        return fvCaseId;
    }

    public void setFvCaseId(int fvCaseId ) {
        this.fvCaseId = fvCaseId;
    }

    @Override
    public String toString() {
        return "Weo5sfv1 [personPin =" + personPin + " ,fvRc =" + fvRc + " ,fvCaseId =" + fvCaseId+ "]";
    }
}