package com.oscar.swv.dataobject;

import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;

/*************************************************************************
 *
 * OSCAR CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * OSCAR is a trademark of OSCAR Company.
 *
 * Copyright © 2017 OSCAR. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of OSCAR
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to OSCAR and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from OSCAR.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public class Weo6nfqe   implements Serializable {

    private String envTr;
    private String applicId;
    public String getEnvTr() {
        return envTr;
    }

    public void setEnvTr(String envTr ) {
        this.envTr = envTr;
    }

    public String getApplicId() {
        return applicId;
    }

    public void setApplicId(String applicId ) {
        this.applicId = applicId;
    }

    @Override
    public String toString() {
        return "Weo6nfqe [envTr =" + envTr + " ,applicId =" + applicId+ "]";
    }
}