package com.swv.oscar.service.batch.impl;

import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Service;

import com.swv.oscar.dataobject.batch.Weo0neom;
import com.swv.oscar.dataobject.batch.Weo0neomBO;
import com.swv.oscar.exceptions.OscarBusinessException;
import com.swv.oscar.service.batch.IWeo0neomService;
import com.swv.oscar.shared.set.AppConstants;
import com.swv.oscar.util.MappingHelper;
import com.swv.oscar.util.OscarLogger;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 *Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
@Service
public class Weo0neomServiceImpl implements  IWeo0neomService {

	private static final OscarLogger LOGGER = OscarLogger.create(Weo0neomServiceImpl.class);

	String query = null;
	/**
	 * Method execute
	 * @param weo0neomBOReq
	 * @return weo0neomBOResp
	 * @throws OscarBusinessException
	 */
	public Weo0neomBO execute(Weo0neomBO weo0neomBOReq) throws OscarBusinessException {
		LOGGER.debug(AppConstants.REQUEST+weo0neomBOReq);
		Weo0neomBO weo0neomBOResp = null;
		List<Weo0neom> weo0neomList = null;
		try {
			weo0neomBOResp =  new Weo0neomBO();
			Weo0neom weo0neom = (Weo0neom) weo0neomBOReq.getFirst(weo0neomBOReq.getWeo0neom());
			//
			// WEO0NEOM - RETURNS THE EOM DEPENDING MONTH-OPTION
			//   MONTH-OPTION = P , PREVIOUS MONTH
			//                  C , CURRENT MONTH
			//                  N , NEXT MONTH
			//
			//
			weo0neom.setRc(0);
			weo0neomList = new ArrayList<>();
			if(weo0neom != null){
				weo0neom.setDateA(weo0neomBOReq.getWeo0neom().get(0).getDateIn());
			}
			if(MappingHelper.getDate(weo0neom.getDateA(), "yyyy.MM.dd") == null) {
				weo0neom.setRc(20);
				weo0neomList.add(weo0neom);
				weo0neomBOResp.setWeo0neom(weo0neomList);
				return weo0neomBOResp;
			}
			//
			if( weo0neom.getDateA() != null){
				weo0neom.setYyyyMm(weo0neom.getDateA().trim().substring(0,7));
			}
			String currentlydate = weo0neom.getDateA().trim();
			weo0neom.setYyyy(Integer.valueOf(currentlydate.substring(0, 4)));
			weo0neom.setMm(Integer.valueOf(currentlydate.substring(5, 7)));
			weo0neom.setI(Integer.valueOf(currentlydate.substring(8, 10)));
			switch (weo0neom.getMonthOption()) {
			case "P":
				weo0neom.setMm(weo0neom.getMm()-1);
				break;
			case "C":
				break;
			case "N":
				weo0neom.setMm(weo0neom.getMm()+1);
				break;
			default:
				/* Weo0cerr 310  = new Weo0cerr();
                weo0cerr.execute();*/
				break;
			}
			//
			if(weo0neom.getMm() == 0) {
				weo0neom.setMm(12);
				weo0neom.setYyyy(weo0neom.getYyyy()-1);
			} else {
				if(weo0neom.getMm() == 13) {
					weo0neom.setMm(1);
					weo0neom.setYyyy(weo0neom.getYyyy()+1);
				}
			}
			//
			
			/*			weo0neom.setDateA(weo0neom.getYyyyMm().substring(i));
			for(int i = weo0neom.getYyyyMm().length(); i > weo0neom.getYyyyMm().length()-4 ; i--) {
				weo0neom.setDateA(weo0neom.getYyyyMm().substring(i));
			}*/
			weo0neom.setDateA(weo0neom.getYyyy()+"."+weo0neom.getMm()+"."+weo0neom.getI());
			if(weo0neom.getDateA().length() != 10){
				if(String.valueOf(weo0neom.getMm()).length() != 2){
					weo0neom.setDateA(weo0neom.getYyyy()+".0"+weo0neom.getMm()+"."+weo0neom.getI());	
					weo0neom.setDateA(weo0neom.getDateA().trim());
				}
				if(weo0neom.getDateA().length() == 9 ){
					weo0neom.setDateA(weo0neom.getDateA().substring(0, 7)+".0"+weo0neom.getI());	
					weo0neom.setDateA(weo0neom.getDateA().trim());
				}
			}else{
				weo0neom.setDateA(weo0neom.getDateA().trim());
			}
			//
			if(MappingHelper.getDate(weo0neom.getDateA(), "yyyy.MM.dd") == null) {
				return weo0neomBOResp;
			}
			//
			weo0neomList.add(weo0neom);
			weo0neomBOResp.setWeo0neom(weo0neomList);
			weo0neom.setDateOut(weo0neom.getDateA());
			// End of list
		}
		catch (Exception ex) {
			LOGGER.error("Error:" + ex);
			throw new OscarBusinessException(ex);
		}
		LOGGER.debug("Response:"+weo0neomBOResp);
		return weo0neomBOResp;
	}
}