package com.swv.oscar.service.batch.impl;

import java.util.List;

import org.springframework.stereotype.Service;

import com.swv.oscar.dataobject.batch.Weo0nenv;
import com.swv.oscar.dataobject.batch.Weo0nenvBO;
import com.swv.oscar.dataobject.common.BaseBO;
import com.swv.oscar.exceptions.OscarBusinessException;
import com.swv.oscar.service.batch.IWeo0nenvService;
import com.swv.oscar.shared.set.AppConstants;
import com.swv.oscar.util.OscarLogger;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 *Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
@Service
public class Weo0nenvServiceImpl implements  IWeo0nenvService {

	private static final OscarLogger LOGGER = OscarLogger.create(Weo0nenvServiceImpl.class);

	String query = null;
	/**
	 * Method execute
	 * @param weo0nenvBOReq
	 * @return weo0nenvBOResp
	 * @throws OscarBusinessException
	 */
	public Weo0nenvBO execute(BaseBO weo0nenvBOReq) throws OscarBusinessException {
		LOGGER.debug(AppConstants.REQUEST+weo0nenvBOReq);
		Weo0nenvBO weo0nenvBOResp = null;
		Weo0nenv weo0nenv = null;
		List<Weo0nenv> weo0nenvList = null;
		try {
/*			weo0nenvBOResp =  new Weo0nenvBO();
			weo0nenv = new Weo0nenv();
			//Weo0nenv weo0nenv = (Weo0nenv) weo0nenvBOReq.getFirst(weo0nenvBOReq.getWeo0nenv());
			// WEO0NENV
			//
			//
			   TODO ATMA commented         Usr0010n usr0010n  = new Usr0010n();
            usr0010n.execute(weo0nenv.getFname(*) ,weo0nenv.getDbt(*) ,weo0nenv.getFnrt(*) ,weo0nenv.getHname(*) ,weo0nenv.getQty());
			//
			weo0nenv.setI(weo0nenv.getFname().indexOf("USER"));
			//TODO #FNAME(*)FOR'USER'GIVINGINDEX#I$
			int i = weo0nenv.getI();
			if(weo0nenv.getI() == 0) {
				weo0nenv.setRc(1);
			} else {
				if(weo0nenv.getDbt() == 001 && weo0nenv.getFnrt() == 011) {
					weo0nenv.setEnv("PROD");
					weo0nenv.setRc(0);
				}
				if(weo0nenvDbtweo0nenvI.equalsIgnoreCase(002) && weo0nenvFnrtweo0nenvI.equalsIgnoreCase(011) && applicId.equalsIgnoreCase("DEVLLIB") || 
						applicId.equalsIgnoreCase("DEVLLIBS")) {
					weo0nenv.setEnv("DEVL");
					weo0nenv.setRc(0);
				}
				if(weo0nenvDbtweo0nenvI.equalsIgnoreCase(002) && weo0nenvFnrtweo0nenvI.equalsIgnoreCase(011) && applicId.equalsIgnoreCase("TESTLIB") || 
						applicId.equalsIgnoreCase("TESTLIBS")) {
					weo0nenv.setEnv("DEVL");
					weo0nenv.setRc(0);
				}
				if(weo0nenvDbtweo0nenvI.equalsIgnoreCase(002) && weo0nenvFnrtweo0nenvI.equalsIgnoreCase(011) && applicId.equalsIgnoreCase("CERTLIB") ||
						applicId.equalsIgnoreCase("CERTLIBS")) {
					weo0nenv.setEnv("TEST");
					weo0nenv.setRc(0);
				}
				if(weo0nenvDbtweo0nenvI.equalsIgnoreCase(002) && weo0nenvFnrtweo0nenvI.equalsIgnoreCase(011) && applicId.equalsIgnoreCase("USERLIB") || 
						applicId.equalsIgnoreCase("USERLIBS")) {
					weo0nenv.setEnv("USER");
					weo0nenv.setRc(0);
				}
				if(weo0nenvDbtweo0nenvI.equalsIgnoreCase(010) && weo0nenvFnrtweo0nenvI.equalsIgnoreCase(213)) {
					weo0nenv.setEnv("DEVL");
					weo0nenv.setRc(0);
				}
				if(weo0nenvDbtweo0nenvI.equalsIgnoreCase(020) && weo0nenvFnrtweo0nenvI.equalsIgnoreCase(213)) {
					weo0nenv.setEnv("DEVL");
					weo0nenv.setRc(0);
				}
				else{
					weo0nenv.setRc(2);
					weo0nenv.setEnv("????");
				}
			}
			
			weo0nenvList.add(weo0nenv);
			weo0nenvBOResp.setWeo0nenv(weo0nenvList);*/

			// End of list
		} catch (Exception ex) {
			LOGGER.error("Error:" + ex);
			throw new OscarBusinessException(ex);
		}
		LOGGER.debug("Response:"+weo0nenvBOResp);
		return weo0nenvBOResp;
	}
}