package com.swv.oscar.repositories;

import com.swv.oscar.dataobject.common.Weo0s002BO;
import com.swv.oscar.exceptions.OscarDataAccessException;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 * Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :

public interface IWeo0s002Repository {


    public Weo0s002BO executeCheckUpdateAccessQuery0(String query) throws OscarDataAccessException;

    public Weo0s002BO executeCheckUpdateAccessQuery1(String query) throws OscarDataAccessException;

    public Weo0s002BO executeGetRegionsQuery2(String query) throws OscarDataAccessException;

    public Weo0s002BO executeGetRegionsQuery3(String query) throws OscarDataAccessException;

    public Weo0s002BO executeCheckModeQuery4(String query) throws OscarDataAccessException;

    public Weo0s002BO executeGetSpluCaseloadQuery5(String query) throws OscarDataAccessException;
}