package com.swv.oscar.repositories;

import com.swv.oscar.dataobject.batch.Weo2p57aBO;
import com.swv.oscar.exceptions.OscarDataAccessException;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 * Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :

public interface IWeo2p57aRepository {


    public Weo2p57aBO executeQuery0(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeUpdateQuery1(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeReadCasesQuery2(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeReadCasesQuery3(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeReadCasesQuery4(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeReadCasesQuery5(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeCalcLine1Query6(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeCalcLine1Query7(String query) throws OscarDataAccessException;

    public Weo2p57aBO executePriorOblgStatsQuery8(String query) throws OscarDataAccessException;

    public Weo2p57aBO executePriorOblgStatsQuery9(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeCheckForHcOrdersQuery10(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeCheckFyEndCaseStatusQuery11(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeCheckFyEndCaseTypeQuery12(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeCheckFyEndCaseTypeQuery13(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeCheckFyEndOosTypeQuery14(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeCheckChildAgeQuery15(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeCheckHearingQuery16(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeCheckGrantAmountQuery17(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeCheckForCsjaMsjaOnlyCasesQuery18(String query) throws OscarDataAccessException;

    public Weo2p57aBO executeCheckForCsjaMsjaOnlyCasesQuery19(String query) throws OscarDataAccessException;

	public Weo2p57aBO insertQuery(String query)  throws OscarDataAccessException;

}