package com.swv.oscar.service.common;

import com.swv.oscar.dataobject.common.BaseBO;
import com.swv.oscar.dataobject.common.Weo0fcnlBO;
import com.swv.oscar.exceptions.OscarBusinessException;

/*************************************************************************
 *
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * HCL is a trademark of HCL Company.
 *
 *Copyright © 2017 HCL. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public interface IWeo0fcnlService {

    public Weo0fcnlBO execute(BaseBO weo0fcnlBOReq) throws OscarBusinessException;
    public Weo0fcnlBO executeENTR(Weo0fcnlBO weo0fcnlBOReq) throws OscarBusinessException;
    public Weo0fcnlBO resetGlobals(Weo0fcnlBO weo0fcnlBOReq) throws OscarBusinessException;
}