package com.swv.oscar.service.common.impl;

import org.springframework.stereotype.Service;

import com.swv.oscar.dataobject.common.BaseBO;
import com.swv.oscar.dataobject.common.Weo0nctsBO;
import com.swv.oscar.exceptions.OscarBusinessException;
import com.swv.oscar.service.common.IWeo0nctsService;
import com.swv.oscar.shared.set.AppConstants;
import com.swv.oscar.util.OscarLogger;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 *Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
@Service
public class Weo0nctsServiceImpl implements  IWeo0nctsService {

    private static final OscarLogger LOGGER = OscarLogger.create(Weo0nctsServiceImpl.class);

    String query = null;
    /**
     * Method execute
     * @param weo0nctsBOReq
     * @return weo0nctsBOResp
     * @throws OscarBusinessException
     */
    public Weo0nctsBO execute(BaseBO weo0nctsBOReq) throws OscarBusinessException {
        LOGGER.debug(AppConstants.REQUEST+weo0nctsBOReq);
        Weo0nctsBO weo0nctsBOResp = null;
        try {
            weo0nctsBOResp =  new Weo0nctsBO();
            /* TODO  Weo0ncts weo0ncts = (Weo0ncts) weo0nctsBOReq.getFirst(weo0nctsBOReq.getWeo0ncts()); */
            // WEO0NCTS
            //
            //
            /* TODO need to find a way to Do this     weo0ncts.setCurrentTs( current timestamp); */
            //
        } catch (Exception ex) {
            LOGGER.error("Error:" + ex);
            throw new OscarBusinessException(ex);
        }
        LOGGER.debug("Response:"+weo0nctsBOResp);
        return weo0nctsBOResp;
    }
}