package com.swv.oscar.service.common.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.swv.oscar.dataobject.common.Weo0s001;
import com.swv.oscar.dataobject.common.Weo0s001BO;
import com.swv.oscar.exceptions.OscarBusinessException;
import com.swv.oscar.repositories.IWeo0s001Repository;
import com.swv.oscar.service.common.IWeo0s001Service;
import com.swv.oscar.shared.set.AppConstants;
import com.swv.oscar.util.OscarLogger;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 *Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
@Service
public class Weo0s001ServiceImpl implements  IWeo0s001Service {

	private static final OscarLogger LOGGER = OscarLogger.create(Weo0s001ServiceImpl.class);

	@Autowired
	private IWeo0s001Repository weo0s001Repository;

	public void setWeo0s001Repository(IWeo0s001Repository weo0s001Repository) {
		this.weo0s001Repository = weo0s001Repository;
	}

	String query = null;
	/**
	 * Method execute
	 * @param weo0s001BOReq
	 * @return weo0s001BOResp
	 * @throws OscarBusinessException
	 */
	public Weo0s001BO execute(Weo0s001BO weo0s001BO) throws OscarBusinessException {
		LOGGER.debug(AppConstants.REQUEST+weo0s001BO);
		Weo0s001BO weo0s001BOResp = null;
		try {
			//
			// SIGNED OUT:                                 DATE:
			//
			// WEO0S001 -- NAVIGATE OUT.
			//
			// NAME       DATE    DESCRIPTION
			//
			// STETZ    03-21-01  DELETED WEO0LCMD (NOT BEING USED). INSERTED
			//                    WEO0L002.
			// MALONE   06-23-10  #122861: FIXED TO HANDLE NEW DJS REFERRAL
			//                    PROCESSING
			//
			//
			//
		} catch (Exception ex) {
			LOGGER.error("Error:" + ex);
			throw new OscarBusinessException(ex);
		}
		LOGGER.debug("Response:"+weo0s001BO);
		return weo0s001BO;
	}

	/**
	 * Method navigateOut
	 * @param weo0s001BOReq
	 * @return weo0s001BOResp
	 * @throws OscarBusinessException
	 */
	public Weo0s001BO navigateOut(Weo0s001BO weo0s001BO) throws OscarBusinessException {
		LOGGER.debug(AppConstants.REQUEST+weo0s001BO);
		Weo0s001BO weo0s001BOResp = null;
		try {
			Weo0s001 weo0s001 = (Weo0s001) weo0s001BO.getFirst(weo0s001BO.getWeo0s001());
			if(weo0s001.getgStackedPanel().equalsIgnoreCase(" ")) {
				query = "select parentPanelId  from weovpanelDesc where panelId = weo0s001.getgPanel()";
				weo0s001BOResp = weo0s001Repository.executeNavigateOutQuery0(query);
				weo0s001.setrPanel(weo0s001BOResp.getWeo0s001().get(0).getgPanel());
				if(weo0s001.getrPanel().equalsIgnoreCase("XXXX")) {
					weo0s001.setrPanel("MAIN");
				}
				weo0s001.setCom( "DISPLAY" + weo0s001.getrPanel());
				weo0s001.setgCommand(weo0s001.getCom());
				/*TODO validateCommand(weo0s001BOResp);*/
			} else {
				if(weo0s001.getgStackedMode().equalsIgnoreCase("A") || weo0s001.getgStackedMode().equalsIgnoreCase("M")) {
					weo0s001.setgAttr("M");
				} else {
					weo0s001.setgAttr("D");
				}
				if(weo0s001.getgPanel().equalsIgnoreCase("DJSR")) {
					query = "select A  caseDisplayNbr  from weovcase A , weovperson B , weovcaseChild C , weovperson p1 where b.setSsn(weo0s001.getgPermSsn()) && b.setPin(C.getPin()) && c.setCaseId(A.getCaseId()) && a.setCtkrPin(p1.getPin()) && p1.setFirstName(\"DIVISION OF\") && p1.setLastName(\"JUVENILE SERVICES\")";
					weo0s001BOResp = weo0s001Repository.executeNavigateOutQuery1(query);
					if(weo0s001BOResp.getWeo0s001() != null && !weo0s001BOResp.getWeo0s001().isEmpty()) {
						if(weo0s001.getCaseDisplayNbr().equalsIgnoreCase(" ")) {
							weo0s001.setCom("DISPLAY APPL 999");
						} else {
							weo0s001.setCom( "DISPLAY APPL " + weo0s001.getCaseNbr());
						}
					}
				} else {
					weo0s001.setCom( "DISPLAY" + weo0s001.getgStackedPanel());
				}
				// MLM -END- 06-23-10

				/*TODO   weo0s001.setgStackedPanel125(weo0s001.setgStackedPanel(226));*/
				weo0s001.setgStackedPanel(null);
				weo0s001.setgCommand(weo0s001.getCom());
				/*TODO    validateCommand(weo0s001BOResp);*/
			}
		} catch (Exception ex) {
			LOGGER.error("Error:" + ex);
			throw new OscarBusinessException(ex);
		}
		LOGGER.debug("Response:"+weo0s001BO);
		return weo0s001BO;
	}
}