package com.swv.oscar.service.common.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.swv.oscar.dataobject.common.BaseBO;
import com.swv.oscar.dataobject.common.Weo0fcnl;
import com.swv.oscar.dataobject.common.Weo0fcnlBO;
import com.swv.oscar.exceptions.OscarBusinessException;
import com.swv.oscar.repositories.IWeo0fcnlRepository;
import com.swv.oscar.service.common.IWeo0fcnlService;
import com.swv.oscar.shared.set.AppConstants;
import com.swv.oscar.util.NaturalUtil;
import com.swv.oscar.util.OscarLogger;

/*************************************************************************
 *
 * HCL CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * HCL is a trademark of HCL Company.
 *
 *Copyright © 2017 HCL. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of HCL
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to HCL and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from HCL.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
@Service
public class Weo0fcnlServiceImpl implements  IWeo0fcnlService {

	private static final OscarLogger LOGGER = OscarLogger.create(Weo0fcnlServiceImpl.class);

	@Autowired
	private IWeo0fcnlRepository weo0fcnlRepository;

	public void setWeo0fcnlRepository(IWeo0fcnlRepository weo0fcnlRepository) {
		this.weo0fcnlRepository = weo0fcnlRepository;
	}

	String query = null;
	/**
	 * Method execute
	 * @param weo0fcnlBOReq
	 * @return weo0fcnlBOResp
	 * @throws OscarBusinessException
	 */
	public Weo0fcnlBO execute(BaseBO weo0fcnlBOReq) throws OscarBusinessException {
		LOGGER.debug(AppConstants.REQUEST+weo0fcnlBOReq);
		Weo0fcnlBO weo0fcnlBOResp = null;
		try {
			weo0fcnlBOResp =  new Weo0fcnlBO();
			//
			// CHECKED OUT BY:
			//  WEO0FCNL  CANCEL ROUTINE FOR FOSTER CARE
			//  -----------------
			//
			//
			//  DATE       USER     DESCRIPTION
			//
			// 11-28-1998  MARCUM   INITIAL DEVEOPMENT
			//
			//
			if((NaturalUtil.getSystemKey().equalsIgnoreCase("ENTR") || NaturalUtil.getSystemKey().equalsIgnoreCase("PF12"))) {
				//TODO REINPUT'Invalid key was hit'
			}
			//
		} catch (Exception ex) {
			LOGGER.error(AppConstants.ERROR + ex);
			throw new OscarBusinessException(ex);
		}
		LOGGER.debug(AppConstants.RESPONSE+weo0fcnlBOResp);
		return weo0fcnlBOResp;
	}

	/**
	 * Method executeENTR
	 * @param weo0fcnlBOReq
	 * @return weo0fcnlBOResp
	 * @throws OscarBusinessException
	 */
	public Weo0fcnlBO executeENTR(Weo0fcnlBO weo0fcnlBOReq) throws OscarBusinessException {
		LOGGER.debug(AppConstants.REQUEST+weo0fcnlBOReq);
		Weo0fcnlBO weo0fcnlBOResp = null;
		try {
			weo0fcnlBOResp =  new Weo0fcnlBO();
			Weo0fcnl weo0fcnl = (Weo0fcnl) weo0fcnlBOReq.getFirst(weo0fcnlBOReq.getWeo0fcnl());
			if((weo0fcnl.getChoice().equalsIgnoreCase("1") || weo0fcnl.getChoice().equalsIgnoreCase("2"))) {
				//TODO REINPUT'VALID VALUES ARE "1" OR "2"'MARK*#CHOICE
			}
			if(weo0fcnl.getChoice().equalsIgnoreCase("1")) {
				//TODO BACKOUTTRANSACTION
				/* TODO       cancelRequest(weo0fcnlBOResp); */
			} else {
				// OPTION 2
				if((weo0fcnl.getOpt().equalsIgnoreCase("Y") || weo0fcnl.getOpt().equalsIgnoreCase("N"))) {
					//TODO REINPUT'INVALID OPTION..ENTER "Y" OR "N"'MARK*#OPT
				} else {
					if(weo0fcnl.getOpt().equalsIgnoreCase("Y")) {
						//TODO BACKOUTTRANSACTION
						/* TODO      cancelRequest(weo0fcnlBOResp);*/
						/* TODO      deleteAllPanels(weo0fcnlBOResp); */
						//  weo0fcnl.setgStackedPanel(*null);
						//  weo0fcnl.setgStackedMode(*null);
						weo0fcnl.setgCtId(null);
						weo0fcnl.setgApPin(null);
						weo0fcnl.setgCtPin(null);
						weo0fcnl.setgApId(null);
						weo0fcnl.setgCountyCd(null);
						weo0fcnl.setgApName(null);
						weo0fcnl.setgCtName(null);
						weo0fcnl.setgCaseload(null);
						weo0fcnl.setgCaseType(null);
						weo0fcnl.setgOosCaseType(null);
						weo0fcnl.setgApplicantId(null);
						weo0fcnl.setgCurNbr(null);
						weo0fcnl.setgText1(null);
						weo0fcnl.setgApplFlag("N");
						query = "UPDATE weovfactsHeader SET oscarCaseId = 0 where timeCreated = weo0fcnl.getTimecreated()";
						weo0fcnlBOResp = weo0fcnlRepository.executeExecuteENTRUpdateQuery0(query);
						weo0fcnl.setgCommand("FCNR");
						/*TODO    validateCommand(weo0fcnlBOResp); */
					}
				}
			}
		}
		//
		//
		catch (Exception ex) {
			LOGGER.error(AppConstants.ERROR + ex);
			throw new OscarBusinessException(ex);
		}
		LOGGER.debug(AppConstants.RESPONSE+weo0fcnlBOResp);
		return weo0fcnlBOResp;
	}

	/**
	 * Method resetGlobals
	 * @param weo0fcnlBOReq
	 * @return weo0fcnlBOResp
	 * @throws OscarBusinessException
	 */
	public Weo0fcnlBO resetGlobals(Weo0fcnlBO weo0fcnlBOReq) throws OscarBusinessException {
		LOGGER.debug(AppConstants.REQUEST+weo0fcnlBOReq);
		Weo0fcnlBO weo0fcnlBOResp = null;
		try {
			weo0fcnlBOResp =  new Weo0fcnlBO();
			Weo0fcnl weo0fcnl = (Weo0fcnl) weo0fcnlBOReq.getFirst(weo0fcnlBOReq.getWeo0fcnl());
			//
			weo0fcnl.setgCtId(null);
			weo0fcnl.setgCaseId(null);
			weo0fcnl.setgCaseload(null);
			weo0fcnl.setgCtPin(null);
			weo0fcnl.setgApPin(null);
			weo0fcnl.setgApLast(null);
			weo0fcnl.setgApFirst(null);
			weo0fcnl.setgApMi(null);
			weo0fcnl.setgApMod(null);
			weo0fcnl.setgApSsn(null);
			weo0fcnl.setgFipsNbr(null);
			weo0fcnl.setgCtLast(null);
			weo0fcnl.setgCtFirst(null);
			weo0fcnl.setgCtMi(null);
			weo0fcnl.setgCtMod(null);
			weo0fcnl.setgApplicantId(null);
			weo0fcnl.setgOosCaseType(null);
			weo0fcnl.setgCaseType(null);
			//weo0fcnl.setgStackedPanel(*null);
			//weo0fcnl.setgStackedMode(*null);
			weo0fcnl.setgApplFlag(null);
			weo0fcnl.setgAfdcCommArea(null);
			// End of list
		} catch (Exception ex) {
			LOGGER.error(AppConstants.ERROR + ex);
			throw new OscarBusinessException(ex);
		}
		LOGGER.debug(AppConstants.RESPONSE+weo0fcnlBOResp);
		return weo0fcnlBOResp;
	}
}