package com.swv.oscar.service.common.impl;

import org.springframework.stereotype.Service;

import com.swv.oscar.dataobject.common.BaseBO;
import com.swv.oscar.dataobject.common.Weo0ccnlBO;
import com.swv.oscar.exceptions.OscarBusinessException;
import com.swv.oscar.service.common.IWeo0ccnlService;
import com.swv.oscar.shared.set.AppConstants;
import com.swv.oscar.util.OscarLogger;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 *Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
@Service
public class Weo0ccnlServiceImpl implements  IWeo0ccnlService {

    private static final OscarLogger LOGGER = OscarLogger.create(Weo0ccnlServiceImpl.class);


    String query = null;
    /**
     * Method execute
     * @param weo0ccnlBOReq
     * @return weo0ccnlBOResp
     * @throws OscarBusinessException
     */
    public Weo0ccnlBO execute(BaseBO weo0ccnlBOReq) throws OscarBusinessException {
        LOGGER.debug(AppConstants.REQUEST+weo0ccnlBOReq);
        Weo0ccnlBO weo0ccnlBOResp = null;
        try {
            weo0ccnlBOResp =  new Weo0ccnlBO();
            /*TODO  Weo0ccnl weo0ccnl = (Weo0ccnl) weo0ccnlBOReq.getFirst(weo0ccnlBOReq.getWeo0ccnl());
             WEO0CCNL*/
        } catch (Exception ex) {
            LOGGER.error("Error:" + ex);
            throw new OscarBusinessException(ex);
        }
        LOGGER.debug("Response:"+weo0ccnlBOResp);
        return weo0ccnlBOResp;
    }
}