package com.swv.oscar.service.common.impl;

import org.springframework.stereotype.Service;

import com.swv.oscar.dataobject.common.BaseBO;
import com.swv.oscar.dataobject.common.Weo0cpf5BO;
import com.swv.oscar.exceptions.OscarBusinessException;
import com.swv.oscar.service.common.IWeo0cpf5Service;
import com.swv.oscar.shared.set.AppConstants;
import com.swv.oscar.util.OscarLogger;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 *Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
@Service
public class Weo0cpf5ServiceImpl implements  IWeo0cpf5Service {

    private static final OscarLogger LOGGER = OscarLogger.create(Weo0cpf5ServiceImpl.class);


    String query = null;
    /**
     * Method execute
     * @param weo0cpf5BOReq
     * @return weo0cpf5BOResp
     * @throws OscarBusinessException
     */
    public Weo0cpf5BO execute(BaseBO weo0cpf5BOReq) throws OscarBusinessException {
        LOGGER.debug(AppConstants.REQUEST+weo0cpf5BOReq);
        Weo0cpf5BO weo0cpf5BOResp = null;
        try {
            weo0cpf5BOResp =  new Weo0cpf5BO();
          /*  Weo0cpf5 weo0cpf5 = (Weo0cpf5) weo0cpf5BOReq.getFirst(weo0cpf5BOReq.getWeo0cpf5());
            WEO0CPF5*/
            //TODO REINPUT' '$
        } catch (Exception ex) {
            LOGGER.error("Error:" + ex);
            throw new OscarBusinessException(ex);
        }
        LOGGER.debug("Response:"+weo0cpf5BOResp);
        return weo0cpf5BOResp;
    }
}