package com.swv.oscar.service.batch;

import com.swv.oscar.dataobject.batch.Weo2p57a;
import com.swv.oscar.dataobject.batch.Weo2p57aBO;
import com.swv.oscar.exceptions.OscarBusinessException;

/*************************************************************************
 *
 * SWV CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * SWV is a trademark of SWV Company.
 *
 *Copyright © 2017 SWV. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of SWV
 * and its suppliers, if any. The intellectual and technical concepts contained
 * herein are proprietary to SWV and its suppliers and may be covered by U.S.
 * and Foreign Patents, patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction of this
 * material is strictly forbidden unless prior written permission is obtained
 * from SWV.
 *
 *************************************************************************/
// Author : Generated by ATMA ®
// Revision History :
public interface IWeo2p57aService {

    public Weo2p57aBO execute(Weo2p57aBO weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO setFiscalYear(Weo2p57aBO weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO readCases(Weo2p57aBO weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO calcLine1(Weo2p57a weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO checkLine2(Weo2p57a weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO calcLine2(Weo2p57a weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO calcLine3(Weo2p57a weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO updateOcse157(Weo2p57a weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO calcActiveMonths(Weo2p57aBO weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO priorOblgStats(Weo2p57a weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO checkForHcOrders(Weo2p57a weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO checkFyEndCaseStatus(Weo2p57a weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO checkFyEndCaseType(Weo2p57a weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO checkFyEndOosType(Weo2p57a weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO checkChildAge(Weo2p57a weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO checkHearing(Weo2p57a weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO checkGrantAmount(Weo2p57a weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO checkForCsjaMsjaOnlyCases(Weo2p57a weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO lockTables(Weo2p57aBO weo2p57aBOReq) throws OscarBusinessException;
    public Weo2p57aBO resynchAndRestart(Weo2p57aBO weo2p57aBOReq) throws OscarBusinessException;
}